### ISSUE TITLE
Improve project names, especially for export

### ISSUE THREAD

**Issue by turbolent** [onflow/flow-playground#109]
**Is your feature request related to a problem? Please describe.**

Currently when creating a new playground and exporting it, the name is `project-LOCAL-project`.
When saving the project and exporting it, the name is e.g. `project-cc3a68fc-b117-4aec-93f3-9967e757b383`.

Both seem odd, and cryptic. Maybe we can make them more user-friendly?

**Describe the solution you'd like**

Maybe feed project IDs to a name generator? e.g. something like Docker's name generation: 
https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go

**Comment by 10thfloor** [comment]
Nice. I like this suggestion.
