### ISSUE TITLE
Flow Playground Compiler Errors - Introduction to Cadence

### ISSUE THREAD

**Issue by peter-strauss** [onflow/flow-playground#121]
**Describe the bug**
Due to compiler version mismatch with the example codes, the smart contracts cannot be deployed.

**To Reproduce**
Open [https://play.onflow.org/ce1f7b8e-13fc-4e09-b5fa-db28e20923f1?type=account&id=0](https://play.onflow.org/ce1f7b8e-13fc-4e09-b5fa-db28e20923f1?type=account&id=0) for example, the error: "consider replacing with: 0.0" is thrown.

If a transaction is opened, an error "consider removing this unnecessary force operator" is thrown.

There are errors in multiple examples.

**Expected behavior**
The default smart contracts in the examples have to be updated for the compiler version V0.12.5 .

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 88.0.4324.146

**Comment by 10thfloor** [comment]
@joshuahannan Can we close this as part of the tutorial upgrade pr?

**Comment by joshuahannan** [comment]
Yep I can close this
