### ISSUE TITLE
Exported Playground tutorials fail on `npm install`

### ISSUE THREAD

**Issue by peter-strauss** [onflow/flow-playground#122]
**Describe the bug**
After exporting a smart contract from Flow Playground, for example [https://docs.onflow.org/cadence/tutorial/02-hello-world/](https://docs.onflow.org/cadence/tutorial/02-hello-world/) , an error is thrown when `npm install` is run.

**To Reproduce**
Run `npm install` inside `test` folder.

Result:
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! indigo-apparent-playground@0.0.0 install: `yarn install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the indigo-apparent-playground@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Expected behavior**
The necessary files should be installed if you run `npm install` inside `test` folder.

**Desktop (please complete the following information):**
 - OS: Windows
 - NPM Version: 6.14.9
 - Yarn Version: 1.22.10

**Comment by kerrywei** [comment]
tested in Mac OS X, npm install works for me. 
@peter-strauss is this still an issue for you? if so, it could be a window platform-specific issue

**Comment by alse** [comment]
Tested on mac os 12.5.1 m1 and it worked
