### ISSUE TITLE
Console is not displaying logs defined in init() function for a contract

### ISSUE THREAD

**Issue by joaomiguelpereira** [onflow/flow-playground#125]
Playground at https://play.onflow.org/177a2329-a4f2-48a4-87bd-a91a94d5721e?type=account&id=cbc531da-5614-4c10-9758-259f94cf2125, 

When change my code to 

```
access(all) contract HelloWorld {
   access(all) let greeting: String
    init() {
        log("Init")
        self.greeting = "Hello, World!"
    }

    access(all) fun hello(): String {
        return self.greeting
    }
}
```

And if I deploy the contract, I was expecting to see the log line "Init" in the console, but just prints:

```
21:18:19  Deployment Deployed Contract To: 0x01
```

**Comment by bthaile** [comment]
Note: 
events and logs are coming from api. They need to be displayed in the UI.
