### ISSUE TITLE
Parse url hash value to enable code highlight

### ISSUE THREAD

**Issue by MaxStalker** [onflow/flow-playground#129]
**Is your feature request related to a problem? Please describe.**
Sometimes you need to share a project big block of code (let's say full contract) and highlight only specific block of code, which answers the question he asked.

**Describe the solution you'd like**
Github have selection for source code (for example: https://github.com/onflow/flow-playground/blob/master/babel.config.js#L3-L5) - we can implement something similar. Highlighting portion of code with Monaco editor tools and scrolling the block into view.

**Comment by bthaile** [comment]
This feature has been released, closing
