### ISSUE TITLE
Add ability to add more accounts to Playground

### ISSUE THREAD

**Issue by timongll** [onflow/flow-playground#133]
Right now FlowPlayground only has 4 accounts available. 
However, many projects like https://github.com/dapperlabs/nba-smart-contracts/tree/master/contracts require more than 4 accounts (6 for nbats) to test all the contracts

Add ability to add more dummy accounts, just like how you are able to add transaction/script templates

**Comment by srinjoyc** [comment]
Start projects with 8 accounts (only show 3 - the minimum for the tutorials), and allow users to add more as needed via the UI. @MaxStalker

**Comment by MaxStalker** [comment]
I have started working on this issue. 

Solution would allow to increase/reduce number of visible accounts, allowing to deploy more than 5 accounts at once. Reducing number of accounts would simply hide latest visible account without affecting it's state or deployed contracts. It won't be possible to remove specific account, cause this could create unnecessary complexity with shifting indexes/addresses of the accounts.

I identified pieces that need to be adjusted and currently working on back-end implementation of this solution. You can keep track of it here - https://github.com/onflow/flow-playground-api/issues/22

**Comment by MaxStalker** [comment]
Work on this issue is stalled in favor of other critical pieces of Playground - Language Server integration and interaction, specifically. I will post to this thread when there will be more progress on the issue.

**Comment by kerrywei** [comment]
per confirmed with Max, this task will be put to backlog

**Comment by neil-ptr** [comment]
@MaxStalker Is it ok if I take this issue?

**Comment by MaxStalker** [comment]
@neilZon absolutely! hit me up, I will give you all the info I have found how to enable this ;)
