### ISSUE TITLE
Show popup with "No Cookies Enabled" info

### ISSUE THREAD

**Issue by MaxStalker** [onflow/flow-playground#135]
We are getting quite common question, when people can't save their playground or deploy code, because they have cookies disabled. We have a style for this popup on `Export Project` - just need to add detection.

Should be pretty easy to do with something like this for cookie detection:
https://stackoverflow.com/questions/4603289/how-to-detect-that-javascript-and-or-cookies-are-disabled

**Comment by 10thfloor** [comment]
Submitted this PR: https://github.com/onflow/flow-playground/pull/136

**Comment by kerrywei** [comment]
Verified the solution works. closing this issue
