### ISSUE TITLE
Location Provider Error

### ISSUE THREAD

**Issue by hichana** [onflow/flow-playground#164]
**Describe the bug**
An error that appears to be related to the router functionality appears in the web console. The functionality of the playground is not noticeably effected.

**To Reproduce**
From 'master' branch, load the playground and open the console. to find the error.

**Expected behavior**
No error would appear.

**Screenshots**
<img width="484" alt="Screen Shot 2021-10-04 at 11 12 57" src="https://user-images.githubusercontent.com/8943047/135783768-4eae578e-b873-457b-9f26-bcbad3abcbcb.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX big sur
 - Browser: Chrome
 - Version 94

**Additional context**
I brought this and other console errors to the attention of @psiemens who indicated they could all be consolidated into a tier3 FLIP bounty.

**Comment by alse** [comment]
Fixed
