### ISSUE TITLE
React state update is attempted on unmounted component

### ISSUE THREAD

**Issue by hichana** [onflow/flow-playground#165]
**Describe the bug**
A react state update is being attempted on an unmounted component, probably during an asynchronous operation, and is throwing an error in the web console.

**To Reproduce**
From 'master' branch, load the playground and open the console. to find the error.

**Expected behavior**
There wouldn't be an error.

**Screenshots**
<img width="484" alt="Screen Shot 2021-10-04 at 11 13 48" src="https://user-images.githubusercontent.com/8943047/135783922-5b779b19-84ce-42e5-a268-4365762f00c7.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX big sur
 - Browser: Chrome
 - Version 94

**Additional context**
I brought this and other console errors to the attention of @psiemens who indicated they could all be consolidated into a tier3 FLIP bounty.

**Comment by alse** [comment]
Fixed
