### ISSUE TITLE
Multiple Keys error throws in browser console

### ISSUE THREAD

**Issue by hichana** [onflow/flow-playground#166]
**Describe the bug**
A react component is using the same keys for multiple nested components, causing a multiple keys error. It doesn't seem to effect the functionality of the playground. There are multiple of the same error thrown in the browser, tho I am only adding a screenshot for the first one here below.

**To Reproduce**
From 'master' branch, load the playground and open the console. to find the error.

**Expected behavior**
That there wouldn't be an error.

**Screenshots**
<img width="492" alt="Screen Shot 2021-10-04 at 11 16 24" src="https://user-images.githubusercontent.com/8943047/135784122-558ab06a-d6b8-4b18-8b88-415e384927f7.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX big sur
 - Browser: Chrome
 - Version 94

**Additional context**
I brought this and other console errors to the attention of @psiemens who indicated they could all be consolidated into a tier3 FLIP bounty.

**Comment by alse** [comment]
Fixed
