### ISSUE TITLE
playround script result output is hidden by default

### ISSUE THREAD

**Issue by kerrywei** [onflow/flow-playground#178]
**Describe the bug**

**To Reproduce**
1. go to https://docs.onflow.org/cadence/tutorial/06-marketplace-compose/ 
2. click the playground link at the top
3. deploy contracts to account 1, 2, and 3, then run transaction 1 and 2, and finally run script 3. 

**Expected behavior**
The log console should display scroll bar if the output is too long, however, the scroll bar of the log console is hidden by default, unless you explicitly scroll horizontally to the right to reveal it. This can make using the playground confusing as part of the output is hidden by default and there is no way to tell it's because user needs to scroll down

![Screen Shot 2021-11-07 at 10 54 13 PM](https://user-images.githubusercontent.com/91617737/140683036-7d207727-dd11-4518-87f5-ea9fde6bafdb.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X 11.6.1
 - Browser: Chrome 95.0.4638.69

**Comment by devbugging** [comment]
solved
