### ISSUE TITLE
'panic' function on borrowed capability causes some resources not to show up in resources explorer in playground

### ISSUE THREAD

**Issue by hichana** [onflow/flow-playground#185]
The new Playground UI with expanded resources explorer functionality should display all account storage items for any given account. The new functionality works, but somehow when the 'panic' function is applied to a borrowed capability it causes some resources not to show up in account storage. 

Steps to reproduce:
1. fork the following playground: https://play.onflow.org/7c60f681-40c7-4a18-82de-b81b3b6c7915?type=account&id=0
2. click on the storage icon next to account 0x01, notice storage is empty
3. deploy the 'ExampleToken' contract
4. notice that account 0x01's storage is still empty

Now,  on a new fork of the playground link before step 2, remove line 146 (the `panic`), and then on line 145 add a force unwrap operator, ex `let recipientRef = recipient.borrow()!`. Deploy and watch how account storage shows the 'Minter', 'MainMinter' and 'MainVault' resources properly.

**Comment by bluesign** [comment]
This one is a great issue, @hichana  did you find out the reason ? If not I will debug this one.

**Comment by hichana** [comment]
Hi @bluesign  I didn’t find out the reason unfortunately. @MaxStalker helped me uncover it as I was building the new resources explorer, so he might have some insights.

**Comment by bluesign** [comment]
Seems problem with `runtimeContext.predeclaredValues`, so checker doesn't recognize `panic` command.

**Comment by alse** [comment]
Appears to be fixed in the latest build:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/1160249/190471529-b27a11b2-7692-43d7-868a-73860c55e331.png">
