### ISSUE TITLE
.env.local missing

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-playground#189]
Last flip fest PR removed this file. I think we need to put it back as README refers to it

**Comment by hichana** [comment]
It does need to get added back @bluesign  -- nice catch. 

@10thfloor shall I make a PR for this? Super easy -- the two env vars in the `.env.local` are:

```
PLAYGROUND_API="http://localhost:8080"
AVATAAR_URL="https://us-central1-flow-developer-playground.cloudfunctions.net/avatar/"
```

**Comment by kerrywei** [comment]
> It does need to get added back @bluesign -- nice catch.
> 
> @10thfloor shall I make a PR for this? Super easy -- the two env vars in the `.env.local` are:
> 
> ```
> PLAYGROUND_API="http://localhost:8080"
> AVATAAR_URL="https://us-central1-flow-developer-playground.cloudfunctions.net/avatar/"
> ```

@hichana that would be awesome!

**Comment by hichana** [comment]
Hi @kerrywei, PR #192 created :)
