### ISSUE TITLE
Transaction template validity checking does not refresh on redeploy

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/flow-playground#190]
**Describe the bug**
When I redeploy with a new public method, the transaction template page does not recognize the new method unless I refresh the playground webpage.

**To Reproduce**
1. Load the default Hello World in the Playground.
2. Deploy it. (might not be necessary)
3. Go to the transaction template (necessary) then return to the 0x01 Account.
4. Rename the `hello` method to `goodbye`.
5. Redeploy.
6. Go to the transaction template and change the method from `hello` to `goodbye`.
7. An error is shown, indicating that there is no `goodbye` member. (BUG)
8. Refresh the page.
9. No error is shown. The transaction can be executed.

Notes:
- This bug ONLY occurs when the transaction template has been visited before editing the contract. I hit this bug because I'm making iterative changes.
- There's an easy workaround: refresh the page.

**Expected behavior**
On step #7, no errors are shown. The transaction can be executed.

**Desktop (please complete the following information):**
 - OS: Linux (Arch)
 - Browser: Google Chrome
 - Version: 96.0.4664.45

**Comment by alse** [comment]
Fixed in latest build
