### ISSUE TITLE
Console error when saving current Playground project

### ISSUE THREAD

**Issue by kerrywei** [onflow/flow-playground#191]
**Describe the bug**

**To Reproduce**
1. launch a brand new playground page
2. open developer console
3. click 'Save' button 
4. you will see errors from console. see screenshot below
![Screen Shot 2021-12-16 at 2 49 39 PM](https://user-images.githubusercontent.com/91617737/146440879-19510e90-6bef-42f0-9346-ac37deba7551.png)

**Expected behavior**
No errors when trying to save a playground project

**Desktop (please complete the following information):**
 - OS: Mac OS X 11.6.1 (20G224)
 - Browser: Chrome
 - Version 96.0.4664.110 (Official Build) (x86_64)

**Comment by alse** [comment]
Fixed in latest build
