### ISSUE TITLE
Console content within variable console components has a fixed height

### ISSUE THREAD

**Issue by alxflw** [onflow/flow-playground#200]
**Describe the bug**
I can adjust the console height but the content seems to be fixed to the initial height

**To Reproduce**

https://user-images.githubusercontent.com/97620081/150382264-94f404aa-fbeb-45f6-ba84-9c6d10cf6e7a.mov

**Expected behavior**
Console content is visible when the component height is increased

**Desktop (please complete the following information):**
 - OS: macOC
 - Browser Chrome
 - Version 97

**Comment by MaxStalker** [comment]
I found the culprit of the issue and currently updating the layout.
Unfortunately, it's not a single CSS value to be updated, so takes a bit more time than I anticipated. But should be easier to introduce new changes in the future.
