### ISSUE TITLE
Script/transaction arguments of type string not accepted if quotes are missing

### ISSUE THREAD

**Issue by alxflw** [onflow/flow-playground#202]
**Describe the bug**
If a user is required to enter a script/transaction argument of type String, they will do so without using quotes. As a result, and error is returned.

**To Reproduce**
- Open playground
- Update script to have a String argument
- Run script and enter `test`
- Spinner is shown and console error is logged

**Expected behavior**
String is accepted

**Screenshots**
<img width="1500" alt="Screen Shot 2022-01-20 at 7 12 19 PM" src="https://user-images.githubusercontent.com/97620081/150459339-f0674228-504b-426b-a369-86b02b2b0d8b.png">

**Comment by ObjectPlayer** [comment]
I am also facing same issue, also I am trying to concatenate strings so if I pass quotation marks than that will also be the part of string which is causing issue, so I am using static values instead of passing arguments in scripts ans transaction for string. 

e.g: 

![image](https://user-images.githubusercontent.com/64414441/150677847-48217ef9-bcb7-4f4e-9ef2-794313888e44.png)

**Comment by ObjectPlayer** [comment]
After running playground locally I found that there was an exception in the `send` method at `src/components/Arguments/index.tsx` in the following line 

```
const formatted = await props.languageClient.sendRequest(
      ExecuteCommandRequest.type,
      {
        command: 'cadence.server.parseEntryPointArguments',
        arguments: [
          props.editor.getModel().uri.toString(),
          fixed
        ],
      },
    );
```
that's why it is showing infinite loader, I have added try and catch block after it was working fine.

**Comment by MaxStalker** [comment]
As a matter of fact it was more about how language server is processing string literals. I believe I was able to fix the issue and now it should work as designed.

This should be addresses, when #211 will be merged :)
