### ISSUE TITLE
Mock getCurrentBlock

### ISSUE THREAD

**Issue by alxflw** [onflow/flow-playground#205]
**Is your feature request related to a problem? Please describe.**
Developers might use `getCurrentBlock().timestamp` in contracts, which will error out.

**Describe the solution you'd like**
One could mock the response to return a dummy response, eg `0.0`

**Describe alternatives you've considered**
Developers seem to replace all the instances with dummy variables

**Comment by MaxStalker** [comment]
@alxflw this is not front-end level issue. Should be probably on Cadence or emulator level.
@psiemens or maybe @turbolent should know better about current implementation.
