### ISSUE TITLE
GQL Request Client Error

### ISSUE THREAD

**Issue by ObjectPlayer** [onflow/flow-playground#210]
**Describe the bug**
I was testing the playground locally and follow all the steps that are defined the [READ.ME](https://github.com/onflow/flow-playground). I cloned the project and install all the dependencies, run docker with given command `docker run -e FLOW_DEBUG=true -e FLOW_SESSIONCOOKIESSECURE=false -p 8080:8080 gcr.io/dl-flow/playground-api:latest` after adding .env file all is working fine, but when I try to deploy any contract or run any script or transaction, I am getting following error: 

> Error: GraphQL error: failed to get or create user: failed to load user from session: entity not found

On docker side, I am getting this error: 

> "timestamp":"2022-01-24T07:48:07Z","message":"GQL Request Client Error: \u003cnil\u003e err = input: project failed to get or create user: failed to load user from session: entity not found","severity":"WARNING","context":{"data":{"error":{"message":"failed to get or create user: failed to load user from session: entity not found","path":["project"]}}}}

**To Reproduce**
For reproducing error, you can follow all the steps that I mentioned above.

**Expected behavior**
It should deploy contract and run scripts and transaction successfully

**Screenshots**
playground while deploying contract:
![image](https://user-images.githubusercontent.com/64414441/150747314-0ebcbba6-033d-45e0-9b7e-e06ac2af2402.png)

Terminal screenshot after running docker image
![image](https://user-images.githubusercontent.com/64414441/150747405-07e2641d-cd1d-4be0-be19-e0b9475ed2e6.png)

**Comment by ObjectPlayer** [comment]
You mean running playground api locally ? If yes, than not running playground api locally, I am running docker image which is given in the README

**Comment by justjoolz** [comment]
Are you also running the Google Cloud Datastore emulator?

https://github.com/onflow/flow-playground-api/blob/master/README.md#running-with-datastore-emulator

**Comment by ObjectPlayer** [comment]
@justjoolz  No I didn't run that yet, should I need to run Google Cloud Datastore emulator too ?

**Comment by MaxStalker** [comment]
@ObjectPlayer the way how I run it:
- **Backend**
  - (optional, if you've done it before) clone [playground-api](https://github.com/onflow/flow-playground-api)
  - install all necessary go packages
  - (optional, if you don't have GC CLI installed) Install Google Cloud CLI and datastore emulator
  - run `make start-datastore-emulator`
  - run `make run-datastore`
- **Frontend**
  - (optional, if you've done it before) clone [playground](https://github.com/onflow/flow-playground)
  - install dependencies via `npm install`
  - run dev-server via `npm start`
  
  You, probably, would also need to clear cookies in your browser, cause you can get weird errors like `no entity found` :thinking:

**Comment by ObjectPlayer** [comment]
Thanks @MaxStalker @justjoolz for the help, it was the cookies issue in my browser, once I removed that it was working fine.
