### ISSUE TITLE
Is Playground on testnet possible?

### ISSUE THREAD

**Issue by Bamthelearner** [onflow/flow-playground#214]
Is it possible to have playground to be on testnet?
That way new comers can get to do trxn and execute scripts to interact with contracts on testnet without learning Flow CLI / fcl.

**Comment by bluesign** [comment]
Once I started this adventure, but it was 10x more work than my initial estimated work. 

The main obstacles were storage access, and contract update restrictions. 

But I think it is easier if you can reuse editor, language server etc parts and integrate them to fcl-demo project from Blocto.

**Comment by MaxStalker** [comment]
I'd say it's a HUGE refactor to make it happen and it's much easier to build it from scratch specifically for testnet interaction.
