### ISSUE TITLE
Limit project description to 1mb

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-playground#218]
The google-datastore used to store the objects that contain the contents of Playground projects has a limit of 1.2mb per field.

We need to validate, and provide some feedback to the user if they are entering content into the Playground that exceeds this length. Their project won't save if this limit is exceeded.

This is currently an issue for project descriptions, which are stored on a Project object (with fields limited to 1.2mb in size) in the datastore.

**Comment by kerrywei** [comment]
@10thfloor would this fail silently, or user will receive error on UI?

**Comment by 10thfloor** [comment]
> @10thfloor would this fail silently, or user will receive error on UI?

It fails silently. A savvy user could see the error in the browser console, but no UI feedback is provided.

**Comment by kerrywei** [comment]
is the change deployed @MaxStalker  ?

**Comment by MaxStalker** [comment]
Reopening the issue to confirm it's properly deployed.

**Comment by MaxStalker** [comment]
Feature is deployed to Playground.
