### ISSUE TITLE
Playground deployment

### ISSUE THREAD

**Issue by kerrywei** [onflow/flow-playground#219]
**Describe the solution you'd like**
release all changes since last deployment -- mainly bug fixes

** Definition of Done
- identify list of changes (features or bug fixes) 
- verify the changes work on staging
- release to prod after the verification

**Comment by kerrywei** [comment]
status: pending Max to sync with SRE engineer today to remove the blocker on permission

**Comment by 10thfloor** [comment]
I think this error is because there is no Mixpanel token for the staging environment. 
Indeed we don't want a token for that environment, because we're not capturing events there. 
It's fine to ignore this error, since it doesn't seem to affect the rest of the app.

**Comment by 10thfloor** [comment]
@MaxStalker @kerrywei I deployed these changes to staging. tag: `v0.15.1`

**Comment by MaxStalker** [comment]
@10thfloor need another small review for this PR - https://github.com/onflow/flow-playground/pull/228
