### ISSUE TITLE
Issue when submitting an integer value for a dictionary

### ISSUE THREAD

**Issue by canedy** [onflow/flow-playground#221]
**Describe the bug**
When attempting to pass an argument on the playground for a dictionary that contains an Integer. 

**To Reproduce**
- In the transaction, I added occupant: {Int: String}
- The transaction argument shows the filed, but the value will not accept the integer value. ex. {1,"Bruce"}
- I receive the following "Not a valid argument of type {INT:String}

**Expected behavior**
- I wanted to enter the integer as part of the dictionary. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/2507134/152236943-72af873f-1ec1-43b0-9e83-36f696f9c73f.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version Version 97.0.1072.76 (Official build) (64-bit)

**Additional context**
N/A

**Comment by MaxStalker** [comment]
This is not a valid object notation. Try to replace comma with colon: `{1: "Bruce"}`

**Comment by MaxStalker** [comment]
@canedy was provided solution working for you? :thinking:
