### ISSUE TITLE
Description is losing focus on entry

### ISSUE THREAD

**Issue by MaxStalker** [onflow/flow-playground#230]
Description input is losing focus, when you try to enter anything in it.
Only enters single character and then drops the focus...

**Comment by MaxStalker** [comment]
Apparently this is the issue with placeholder option on SimpleMDE component.
Removing it, brings back editing to normal.
Replicated here - https://codesandbox.io/s/simplemde-placeholder-problem-sts9rd - to ensure it's not Playground issue, but rather something on component side.

**Comment by MaxStalker** [comment]
@kerrywei can we add this issue to current sprint?

**Comment by kerrywei** [comment]
@MaxStalker yeah I agree this is an issue that severely impacts user experience, deserving a fix asap
any chance we can preserve the placeholder, or at least hint the user in some way to indicate the markdown syntax is supported in the description text field?

**Comment by kerrywei** [comment]
@MaxStalker to provide status update

**Comment by kerrywei** [comment]
@MaxStalker  reminder: we want to mark a task closed when the changes are released

**Comment by MaxStalker** [comment]
@kerrywei understood.
I will keep the issue open until we confirm it's properly deployed to production server. Sorry for this mishap :bow:

**Comment by kerrywei** [comment]
@MaxStalker I tried production playground, the losing focus issue is still there. we should plan a release asap to address this

**Comment by MaxStalker** [comment]
Fix for this one is currently building and will be deployed on staging in next 5 minutes.
Once confirmed we would push it to production asap.
