### ISSUE TITLE
Upgrade Cadence version of playground

### ISSUE THREAD

**Issue by LanfordCai** [onflow/flow-playground#237]
**Is your feature request related to a problem? Please describe.**
Current Cadence version of playground is v0.20.0(released on Nov 18, 2021), which is lower than the latest Cadence version(v0.23.2). 
Many new features have applied to Cadence, but we can't use it on playground now due to the laggy of Cadence upgrading.

**Describe the solution you'd like**
Upgrade Cadence version of playground, and upgrade it whenever a new version is available.

<img width="217" alt="image" src="https://user-images.githubusercontent.com/10380321/160355666-d7fd2400-e5a7-46f6-9965-5537ac9ad617.png">

**Comment by kerrywei** [comment]
the cadence version is upgraded to 0.24.3. closing this issue now
