### ISSUE TITLE
Import contract error

### ISSUE THREAD

**Issue by jacob-tucker** [onflow/flow-playground#251]
**Describe the bug**
When you go to import a contract on the playground, one of two things happen:

1. It says there is a missing contract deployment at the specific address
2. It says there are missing digits and token identifiers, if you refresh the page some of the text is missing

**To Reproduce**
Here's what I do that creates the problem:
1. Go to https://play.onflow.org/ (it loads up the HelloWorld example) and deploy HelloWorld to 0x01
2. Go to the script tab and add import HelloWorld from 0x01
3. Click "Execute"

**Desktop (please complete the following information):**
- It says Cadence V0.20.0 in the top right

**Additional context**
I think there's a larger problem with the playground where if you move too fast it will break very easily

**Comment by MaxStalker** [comment]
Hey, @jacob-tucker !
Thank you for filling this issue :bow: 
I think I identified the culprit and currently working on a solution for this issue.
