### ISSUE TITLE
Cadence code completion

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow-playground#26]
The Cadence editor included in the playground implements simple code completion based on naive keyword parsing, but does not have the full knowledge of Cadence syntax required to provide useful code automation.

We would like to investigate ways to display code completion options that are specific to Cadence syntax and features.

## Possible Solution

Integrate Monaco with the Cadence LSP server: https://github.com/onflow/cadence/tree/master/languageserver

**Comment by turbolent** [comment]
Implemented this in the Cadence language server: https://github.com/onflow/cadence/pull/257.

Once that PR is merged, and the integration of the language server into the Playground (#43) is merged, this issue should be done.

**Comment by turbolent** [comment]
The integration of the language server also added support for completion, there is nothing to be done specifically for the Playground.
