### ISSUE TITLE
Playground State is Lagging 

### ISSUE THREAD

**Issue by codingone21** [onflow/flow-playground#260]
**Describe the bug**
State is not updating fast enough to changes, sometimes resulting in reverting changes. Sometimes the errors clear when refreshed multiple times.

**To Reproduce**
There were several instances reported related to this:

Instance 1 
Process: Creating a new transaction in the playground while following a tutorial.
Issue: While typing and naming the transaction, the screen reset and deleted a few lines of code. The playground cleared the name of the transaction, and reverted to New Transaction
Note: Screen reset is probably an accidental refresh, which reverted the code and the transaction name to the previously saved version.

Instance 2
Process: Coding on the Playground
Issue: Playground gave incorrect error on excessive ‘}’ that was actually needed. The error was cleared upon refreshing the screen
Notes: Error with closing brackets are falsely reported, probably due to the state persisting the previously saved cadence code.

Instance 3 
Process: Running transactions with false-positive type errors
Issue: There are type errors (live errors) that won’t allow users to run transactions. After refresh, the error cleared and allowed running transactions, but the console gave errors. After another refresh, all errors are cleared
Notes: Errors are alerted false-positively, and only disappears after multiple refresh attempts.

Instance 4
Process: Deleting a line of code
Issue: Deleting a line of code does not trigger the re-run of the error checker, even though the code has an error in it. When a user deleted the code with the type error, then refreshed the page, the deleted piece would return and retrigger the error.
Notes: Refreshing causes some deleted lines to come back.

Instance 5 - Similar to Instance 3
Process: 
Coding smart contracts in the Playground causing many false type errors (live errors). Seems like each keystroke triggers the type error to be evaluated. (M, Ma, Mas, Mast..)
Refreshing resolved the type errors, and shows the remaining true error to be fixed
The user fixes the remaining error, and Playground shows that it autosaved. 
However, refreshing again results in the code reverting to a state before the fix (Step 2)
Thread: https://axiomzen.slack.com/archives/C03FUAG6SEP/p1652809839024079 
Note: Error persists until refresh, and refresh also causes code to revert.

Instance 6 
Process: 
User sees no live error, but running a transaction results in a console errors.
Refreshing results in the Playground showing live errors, which should have been detected before running.
User copies the original transaction and runs the copy, everything is good.
Thread: https://axiomzen.slack.com/archives/C03FUAG6SEP/p1652810552316699 

Instance 7
Process:
Playground code as Account1 import Account2
Deploy Account2 and quickly switch over to Account1
Account1 shows import error not being able to import from Account2
Refresh page or change editors and come back to Account1’s editor and error has cleared (also the same with transactions that import accounts)

**Expected behavior**
We expect the Playground state to sync before refreshing. For example, we want errors to be un-detected while deleting so that we can execute. 

**Screenshots**
Slack Threads have photos.

**Desktop (please complete the following information):**
 - OS: -
 - Browser: chrome
 - Version: -

**Additional context**
This issue seems to be related to the past fix: Please refer to this document https://github.com/onflow/flow-playground/blob/staging/docs/POST-MORTEM.md

**Comment by alse** [comment]
Fixed by #302
