### ISSUE TITLE
Save button doesn't save consistently and changes are lost :/

### ISSUE THREAD

**Issue by curiosityflow** [onflow/flow-playground#261]
I press the Save button and a message of "Autosaving..." or "All Changes Saved" displays. Sometimes, my changes were indeed saved after I refresh. 

And other times, my changes did not save at all after refreshing (and despite clicking Save and this message displaying). This error happens constantly, and I have lost my changes in different occasions. 

As a result, I have to copy and paste my code into a word doc, then open a new playground to copy my code over and click save again (hoping it would work). This indeed works, but then I encounter the same problem again when clicking the Save button to keep saving my progress.

**Comment by kerrywei** [comment]
the cadence version is upgraded to 0.24.3. closing this issue now

**Comment by alse** [comment]
This should be fixed in the latest build
