### ISSUE TITLE
Embeddable code snippets

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow-playground#27]
**Is your feature request related to a problem? Please describe.**

As a playground user, I would like a way to create embeddable snippets from a playground project. I would like to embed these snippets in blog posts, tutorials and documentation.

**Describe the solution you'd like**

It would be nice if I could create a snippet from any pane in the playground -- a specific account, transaction or script. This snippet could then be embedded as HTML on any webpage. The embedded snippet should display Cadence syntax highlighting. It should also include a link to the original playground project.

**Describe alternatives you've considered**

It's currently possible to create a GitHub Gist that contains Cadence code, but it does not support syntax highlighting and is not runnable in the browser.

**Comment by timmymmit** [comment]
@MaxStalker to add more details about what he will actually implement and what is not included as a part of this issue.

**Comment by MaxStalker** [comment]
Improvements:
- hide buttons if the project is not saved on server side
