### ISSUE TITLE
import contract from transaction or script is broken

### ISSUE THREAD

**Issue by jyxt** [onflow/flow-playground#282]
**Describe the bug**
Imports in Playground is simply broken. Even the hello world example does not work.

**To Reproduce**
- Open play.onflow.org
- Click on 'Click here to start a tutorial'
- Click on 'Hello World'
- Click on 'Say Hello' sample transaction on the sidebar

**Expected behavior**
Should be able to send the transaction (after deploying the contract).

**Screenshots**
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/2034465/182222550-0b109397-0e23-4db1-a872-cb753d2fc034.png">
UI shows problems.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version: 101.0.4951.64 (Official Build) (arm64)

**Additional context**

**Comment by bluesign** [comment]
You need to go account 0x1 and click deploy contract

**Comment by jyxt** [comment]
> You need to go account 0x1 and click deploy contract

I did

**Comment by alse** [comment]
Fixed in latest build
