### ISSUE TITLE
[Refactor] ProjectProvider

### ISSUE THREAD

**Issue by neil-ptr** [onflow/flow-playground#283]
**Is your feature request related to a problem? Please describe.**
This feature is related to the recent playground issues and is a preliminary step in identifying the causes of the playground issues

**Describe the solution you'd like**
Refactor GraphQL CRUD functions (such as `updateProject` see: https://github.com/onflow/flow-playground/blob/staging/src/providers/Project/index.tsx#L139) out of `ProjectProvider` into separate CRUD services (maybe something like `AccountsService`, `TransactionsService`). This is to help improve SRP and testability.

**Comment by fotescodev** [comment]
This effort probably ties into the #501 issue @sideninja @gpavlov2016

**Comment by bthaile** [comment]
As part of playground v2 there were refactors of how state is handled. closing
