### ISSUE TITLE
Transaction and script arguments

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-playground#29]
**Is your feature request related to a problem?**

When creating transaction and script templates, it's currently impossible to use parameterized transaction or scripts due to the fact that there is no way to specify arguments. Values that would otherwise be parameterized must instead be hard-coded, which is tedious for the developer.

**Describe the solution you'd like**

I would like to have the ability to use parameterized transactions and scripts in the playground. Maybe this could be implemented as a set of input fields next to the "Send transaction" button?

**Comment by MaxStalker** [comment]
I've tried different variants with docket panels and I believe undocked (popup-like) will work the best.
For transaction/script arguments, we can parse (either manually or via language server) list of them and populate the fields as user changes the code.  Same for a list of signers - we can hide/show block with signers selection, based on the fact if they are specified in `prepare` block.

Here are some concepts to illustrate the idea how it can work:

- single argument
![transaction - single argument, no signers](https://user-images.githubusercontent.com/3136647/92009864-c74bf800-ed51-11ea-8e1d-5457265703e7.jpg)

- single argument and single signer
![transaction - single argument, single signer](https://user-images.githubusercontent.com/3136647/92009846-c1eead80-ed51-11ea-85ca-1279c43e5935.jpg)

If there will be multiple parameters, we can collapse/expand the view to preserve the space:
![transaction - multiple arguments, single signers, collapsed](https://user-images.githubusercontent.com/3136647/92009921-d7fc6e00-ed51-11ea-9fb8-42e6bb434e10.jpg)

- maybe we can add some `pragma` commented text to enable validation? 🤔 Or we can use common sense and provide built in checks for generic types
![transaction - multiple arguments, single signers, error](https://user-images.githubusercontent.com/3136647/92010039-fcf0e100-ed51-11ea-8d2d-1d7ddd3f6c3d.jpg)

- all cool, you can send transaction now
![transaction - multiple arguments, single signers, cleared](https://user-images.githubusercontent.com/3136647/92010199-31fd3380-ed52-11ea-8264-e1483ac3dc5e.jpg)

- works exactly the same for scripts, sans signers
![script - two arguments](https://user-images.githubusercontent.com/3136647/92010225-3a556e80-ed52-11ea-8ebd-9fd1ed596ff4.jpg)

- we can also allow to move this block around if user prefers to have it somewhere else:
![transaction - single argument, move](https://user-images.githubusercontent.com/3136647/92010415-77216580-ed52-11ea-8754-8cfefc228ed1.jpg)

**Comment by turbolent** [comment]
@MaxStalker These mockups look great! I quite the simplicity of just a text / input field + showing the type for now and limiting it to primitive types (strings, booleans, numbers, addresses) – we can extend this to more types and more specific UI (like a checkbox for a boolean) later

**Comment by turbolent** [comment]
Regarding the signer selection, I think we can keep using the signer selection we already have (two rows: available + selected signers

**Comment by MaxStalker** [comment]
@turbolent right! checkbox - I forgot about this one 😁
We can initially use existing account selection, but me, personally, and members of the community experienced that error, when you select wrong number of accounts, so I thought to explore this idea, that we only show necessary amount of accounts :)

**Comment by turbolent** [comment]
Good point about only allow selection up to the number of signer parameters 👍
