### ISSUE TITLE
Contract examples: Mismatched types error in "Create a Topshot Set" contract

### ISSUE THREAD

**Issue by alse** [onflow/flow-playground#294]
https://open-cadence.onflow.org/?preview=16
https://play.onflow.org/15c1e86e-010c-4a7c-bcfd-98a1bddc36a7?type=tx&id=9e42f1aa-3f25-4ffc-87f0-b9d109e1d851&storage=none

**Describe the bug**
Successfully deployed in 0x02. 0x03 and 0x04, get mismatched types errors when trying to deploy 0x01 . Possibly related to #300

**To Reproduce**
- Deploy 0x02, 0x03, and 0x04
- 0x01 shows multiple errors
- Errors don't go away after refreshing page

**Expected behavior**
0x01 should not have any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/1160249/186207105-a859942a-de69-4e38-bb7e-cf7646c1a3dd.png)

**Desktop**
 - OS: macOS 12.4
 - Browser: Chrome 
 - Version: 104.0.5112.101 (arm64)

**Comment by DylanTinianov** [comment]
New link: https://play.onflow.org/63a7ce9f-3315-4c55-8392-2d626bb8387d?type=account&id=91c4010c-2407-4a3c-a0c1-cc4d3904d9f8&storage=none
