### ISSUE TITLE
Contract examples: NewExampleNFT errors in "Mint NFT" contract

### ISSUE THREAD

**Issue by alse** [onflow/flow-playground#295]
https://open-cadence.onflow.org/?preview=0
https://play.onflow.org/41befd2d-31f3-47f0-ae30-aad776961e31?type=tx&id=7e5fff15-3186-4562-9871-9e9aa99cce66&storage=none

**Describe the bug**
From Playground Bug Hunt:

```Unable to deploy NewExampleNFT contract due to mismatched types. expected `&NonFungibleToken.NFT`, got `NonFungibleToken.NFT?` ```

**To Reproduce**
- Deploy 0x03, 0x04, 0x05, 0x01 
- 0x02 shows mismatched type errors

**Expected behavior**
- 0x02 should be deployable without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/1160249/186210789-884224c7-3728-4d4d-8d2d-0060515bc7c3.png)

**Desktop (please complete the following information):**
- OS: macOS 12.4
- Browser: Chrome
- Version: 104.0.5112.101 (arm64)

**Comment by DylanTinianov** [comment]
New link: https://play.onflow.org/22ef65e1-654d-4ab1-bd82-3712a6fb8877?type=account&id=27ecf409-b82d-43f7-9b94-5c9753bc7abf&storage=none
