### ISSUE TITLE
Fix Playground Sentry errors

### ISSUE THREAD

**Issue by alse** [onflow/flow-playground#297]
**Error 1:** `GraphQL error: failed to update account: rpc error: code = Aborted desc = Aborted due to cross-transaction contention. This occurs when multiple transactions attempt to access the same data, requiring Firestore to abort at least one in order to enforce serializability.`

**Reason:**
- user attempting to deploy to account multiple times in session?
- multiple users attempting to deploy contracts to the same account?
- user attempting to send multiple updates to transaction/script template?
- recreated by spamming `deploy` button

**Investigation notes:**
- 105 events in last 24 hrs by 8 users (717 events in last 30 days)
- same error logged in playground-api sentry dashboard (5.3k events in the last 24 hrs by 0? users)
-  [firestore troubleshooting article](https://cloud.google.com/firestore/docs/troubleshooting#aborted)
- possibly triggered by [UPDATE_ACCOUNT_DEPLOYED_CODE](https://github.com/onflow/flow-playground/blob/20574fb0da68e209b0a08a259c23484597daa9aa/src/api/apollo/mutations.ts#L75) AND/OR [UPDATE_ACCOUNT_DRAFT_CODE](https://github.com/onflow/flow-playground/blob/20574fb0da68e209b0a08a259c23484597daa9aa/src/api/apollo/mutations.ts#L58)
- https://sentry.io/organizations/dapperlabs/issues/3460085293/?project=6391677

**Actions:**
- add monitoring to firestore dashboard
- update playground-api transactions to handle 
- disable button after 1st call?

----
**Error 2:**  `GraphQL error: failed to update script template: failed to update script template: rpc error: code = Aborted desc = Aborted due to cross-transaction contention. This occurs when multiple transactions attempt to access the same data, requiring Firestore to abort at least one in order to enforce serializability.` (likely dupe of 1.)

**Investigation notes:**
- 1.4k events in last 24 hrs by 45 users (37k events in last 30 days)
- see 1.
- recreated by spamming `send` transaction button
- https://sentry.io/organizations/dapperlabs/issues/3459151908/?project=6391677

---
**Error 3:**  `TypeError Cannot read properties of undefined (reading '0')`

**Reason:**
- bad argument input for transaction? 
- user error?
- https://sentry.io/organizations/dapperlabs/issues/3460590666/?project=6391677

**Investigation notes:**
- 5 events in last 24 hrs by 2 users (119 events in last 30 days)
-  occurs when [sending script/transactions ](https://github.com/onflow/flow-playground/blob/staging/src/components/CadenceEditor/ControlPanel/index.tsx#L271)to be executed
- extra error stack :
```
Error: input is not a literal
{
  arguments: [
    {
      code: -32603, 
      data: None, 
      message: input is not a literal, 
      name: Error, 
      stack: 
      Error: input is not a literal
          at https://play.onflow.org/main.js:106:81915
          at https://play.onflow.org/main.js:106:82209
          at https://play.onflow.org/main.js:106:82572
          at r (https://play.onflow.org/main.js:114:322891)
    }
  ], 
  logger: console
}
```

**Action:**
- add input verification?

---
**Error 4:**  `GraphQL error: failed to get accounts: rpc error: code = DeadlineExceeded desc = context deadline exceeded`

**Reason:**
- user? latency issues causing gql calls to timeout?

**Investigation notes:**
- 2 events in last 24 hrs by 2 users ()
-  deadline exceeded = server timeout
- some events are associated with error 1. and some not
- https://sentry.io/organizations/dapperlabs/issues/3461371342/?project=6391677&query=is%3Aunresolved+deadline&statsPeriod=14d

**Action:**
- increase timeout limits?
- addressing error 1 could indirectly fix this?

---
**Error 5:**  `Network error: Failed to fetch`

**Reason:**
- user latency issues?
- 

**Investigation notes:**
- 13 events in last 24 hrs by 8 users (489 events in last 30 days)
-  alt message: `Network error: Response not successful: Received status code 422`
- usually following command: `Cadence Language Client: called execute command: cadence.server.getEntryPointParameters`
- https://sentry.io/organizations/dapperlabs/issues/3460895367/?project=6391677
- https://sentry.io/organizations/dapperlabs/issues/3456720999/?project=6391677

**Action:**
-

**Comment by MrDSGC** [comment]
Created new separate issues #311 #310 #309  so closing this issue.
