### ISSUE TITLE
Content updates for Cadence contract examples

### ISSUE THREAD

**Issue by alse** [onflow/flow-playground#298]
Extracted from Playground Bug Hunt:

https://open-cadence.onflow.org

### "Collection's for holding NFT's"
- [ ] Rename to "Collections for holding NFTS" (#todo: which repo should this be added to?)

### Token Vault
- [ ] Script name not descriptive
- [ ] Account 5: no boilerplate HelloWorld contract

**Comment by MrDSGC** [comment]
Closing since issue should be fixed
