### ISSUE TITLE
Playground error string is difficult to copy

### ISSUE THREAD

**Issue by alse** [onflow/flow-playground#299]
**Describe the bug**
Playground error string is difficult to copy. Clicking the error drags the control panel

**To Reproduce**
Select error text

**Expected behavior**
Text should be selectable

**Screenshots**
![image](https://user-images.githubusercontent.com/1160249/186244972-73646731-7aac-4636-bbe3-5798585ef100.png)

**Desktop (please complete the following information):**
- OS: macOS 12.4
- Browser: Chrome
- Version: 104.0.5112.101 (arm64)

**Comment by MrDSGC** [comment]
To be addressed in design changes. Not relevant to Playground Stability
