### ISSUE TITLE
Inconsistent avatars in UI

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-playground#30]
**Describe the bug**

The playground UI displays inconsistent avatars when creating a new project.

**To Reproduce**

1. Navigate to https://play.onflow.org/
2. Click on "Transaction 1"
3. Notice that the avatars in the account panel (left side) do not match the avatars displayed in the transaction account picker (right side)
4. Click "Save"
5. Refresh the page
6. Notice that the avatars are now in sync

**Expected behavior**

The avatars should be in sync for a new (not yet saved) project.

**Comment by 10thfloor** [comment]
@psiemens @turbolent I believe this got fixed?

**Comment by turbolent** [comment]
Maybe? I haven't really checked specifically. I think we can just close and re-open if it comes up again.

**Comment by caseyturnerarrington** [comment]
@10thfloor @turbolent just wanted to follow up on this: Can we close this issue?

**Comment by caseyturnerarrington** [comment]
Per @10thfloor : closing.
