### ISSUE TITLE
Contract examples: Mismatched types error in "Create A Marketplace" contract

### ISSUE THREAD

**Issue by alse** [onflow/flow-playground#300]
**Describe the bug**
https://play.onflow.org/1d11f838-fc0e-4e7f-86e3-6d1a5a1098e3?type=tx&id=f32eaf35-c6e1-4195-b144-27eef3abda76&storage=none Possibly related to #294

**To Reproduce**
- Deploy 0x01, 0x02, 0x05, refresh page.
- 0x03 and 0x04 have mismatched types errors

**Expected behavior**
0x03 and 0x04 should be deployable withour errors

**Screenshots**
![image](https://user-images.githubusercontent.com/1160249/186250313-5232275d-f3ad-47f3-84a7-81df07ba85a6.png)
![image](https://user-images.githubusercontent.com/1160249/186250344-c3253831-4322-4f39-845b-e2b972863515.png)

**Desktop (please complete the following information):**
- OS: macOS 12.4
- Browser: Chrome
- Version: 104.0.5112.101 (arm64)

**Comment by DylanTinianov** [comment]
New link: https://play.onflow.org/9f2f0aee-490e-4ffb-8f42-1d1067949dee?type=account&id=84aa1c58-bb11-4d12-aab4-5de3c3d0857e&storage=none
