### ISSUE TITLE
The following contracts link to the same playground

### ISSUE THREAD

**Issue by alse** [onflow/flow-playground#301]
Mint NFT: https://play.onflow.org/41befd2d-31f3-47f0-ae30-aad776961e31?type=tx&id=7e5fff15-3186-4562-9871-9e9aa99cce66&storage=none
  Collection's for holding NFT's: https://play.onflow.org/41befd2d-31f3-47f0-ae30-aad776961e31?type=tx&id=88850298-bed1-4bb9-b77e-4df200f76278&storage=none
  Creating Collection For Account: https://play.onflow.org/41befd2d-31f3-47f0-ae30-aad776961e31?type=tx&id=88850298-bed1-4bb9-b77e-4df200f76278&storage=none
  Metadata Views: https://play.onflow.org/41befd2d-31f3-47f0-ae30-aad776961e31?type=script&id=60b68d62-f15e-402e-9048-ef3f27e224af
  Multiple Metadata Views: https://play.onflow.org/41befd2d-31f3-47f0-ae30-aad776961e31?type=script&id=baf002e4-7124-4ffb-894e-5c04e95629de

**Comment by MrDSGC** [comment]
I looked into this and found that this is expected behavior. It looks like groups of tutorials build on each other so maybe we should reformat the cookbook to reflect that. 
![image](https://user-images.githubusercontent.com/23225108/189779865-fb0dfea0-6579-4680-aa2d-5fa05ebdde8e.png)
