### ISSUE TITLE
Playground Type Error

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#310]
**Describe the bug**
`TypeError Cannot read properties of undefined (reading '0')`

Reason:

bad argument input for transaction?
user error?
https://sentry.io/organizations/dapperlabs/issues/3460590666/?project=6391677

- 5 events in last 24 hrs by 2 users (119 events in last 30 days)
- occurs when [sending script/transactions ](https://github.com/onflow/flow-playground/blob/staging/src/components/CadenceEditor/ControlPanel/index.tsx#L271)to be executed
extra error stack :

```Error: input is not a literal
{
  arguments: [
    {
      code: -32603, 
      data: None, 
      message: input is not a literal, 
      name: Error, 
      stack: 
      Error: input is not a literal
          at https://play.onflow.org/main.js:106:81915
          at https://play.onflow.org/main.js:106:82209
          at https://play.onflow.org/main.js:106:82572
          at r (https://play.onflow.org/main.js:114:322891)
    }
  ], 
  logger: console
}
```

**Comment by MrDSGC** [comment]
https://github.com/onflow/flow-playground/blob/staging/src/components/CadenceEditor/ControlPanel/index.tsx#L277
and
https://github.com/onflow/flow-playground/blob/staging/src/components/Arguments/index.tsx#L307

Error is due to LS responding with no data to the `formatted` var. The try/catch errors out and logs to console but the code continues and reaches this Type error attempting to index into `undefined`

![Image](https://user-images.githubusercontent.com/23225108/189956411-bc49f946-b17b-4f27-ab04-804702e7b671.png)

**Comment by fotescodev** [comment]
@MrDSGC what's the plan with this issue? Did we reach an agreement on how to proceed?

**Comment by justinbarry** [comment]
Stale.
