### ISSUE TITLE
Type Mismatch Error

### ISSUE THREAD

**Issue by ashlinSajan** [onflow/flow-playground#313]
Getting issue while deploying contyract on flow PLAYGROUND
let ref = &self.ownedNFTs[id] as auth &NonFungibleToken
   |                        ^^^^^^^^^^^^^^^^^^ expected `NonFungibleToken`, got `NonFungibleToken.NFT?

**Comment by ashlinSajan** [comment]
@MaxStalker Hi Max,
Getting issue while deploying contract on flow PLAYGROUND
let ref = &self.ownedNFTs[id] as auth &NonFungibleToken
| ^^^^^^^^^^^^^^^^^^ expected NonFungibleToken, got `NonFungibleToken.NFT?
Please do find the contract attached.The issue comes from line 55 and 59 of the contract
[HolidaysNFT.txt](https://github.com/onflow/flow-playground/files/9554248/HolidaysNFT.txt)
Please suggest a way to resolve the same

**Comment by alse** [comment]
This looks like a bug in the contract, and is not related to the playground.

You can try something like `let ref = (&self.ownedNFTs[id] as &NonFungibleToken.NFT?)!`
