### ISSUE TITLE
Revisit browser support

### ISSUE THREAD

**Issue by devbugging** [onflow/flow-playground#330]
Currently, if you want to use the playground on safari you get the warning:

`You're currently using an unsupported browser to access the Flow Playground. We hope to support your browser in the future, but for now some features may not function as intended. In order to have the best experience, we recommend you use either Chrome or Firefox to access the Flow Playground.` 

We should revisit why is that so and how to remove this warning.

**Comment by bthaile** [comment]
`Error GraphQL error: user error: not authorized`
Getting this error in safari console. 

After research below, Still doesn't resolve the safari issue. 

```We got a full fix. With advice from Apollo support, we switched out whatwg-fetch for isomorphic-fetch. This allowed us to return to full functionality on Safari/iOS and maintain functionality on Chrome and Firefox.```
https://community.apollographql.com/t/apollo-client-3-6-9-with-graphql-15-8-0-broken-on-webkit-safari-serverparseerror/4550/5

It looks like playground is using `isomorphic-fetch` which has a dep on whatwg-fetch. `isomorphic-fetch` is no longer actively maintained, we'd want to use a different lib.

Could use built in fetch and remove out of date fetch libs.
