### ISSUE TITLE
Investigate possible transaction template caching issue.

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#334]
**Describe the bug**
- Executing a transaction template after updating it may result in the previous version being executing.
- possible caching issue
- Inconsistant and unable to recreate

**To Reproduce**
1. create valid transaction template and execute to confirm result A
2. update transaction template to return different result B
3. immediately execute new transaction

**Expected behavior**
final execution should return result B

**Comment by gpavlov2016** [comment]
One hypothesis is that the Monaco editor state is out of sync with the Apollo cache state

**Comment by MrDSGC** [comment]
fixed
