### ISSUE TITLE
Playground E2E Tests

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#335]
Implement Cypress Test Suite for playground

Test cases:
- deploying contract to account
- executing script template
- executing transaction template
- updating storage of account
-

**Comment by devbugging** [comment]
Can you please link the PR even if WIP to this issue?

**Comment by devbugging** [comment]
Addition: Implement tutorials (possibly fetching the content directly from the source) and make sure they work.

**Comment by devbugging** [comment]
Addition: make sure this runs as part of the CI

**Comment by devbugging** [comment]
Please pull in @alse into this work once he finishes other tasks. Also make sure to architecture it in a way that will be easy to switch to v2. Like said I believe you should just implement UI adapters for each version.

**Comment by MrDSGC** [comment]
[Cypress does not support tabs](https://docs.cypress.io/guides/references/trade-offs#Multiple-tabs). Therefore, clicking `open project` on tutorials will break cypress flow. 
Workaround: begin testing tutorials directly from their saved URL?

Tutorials only exist on production. 
Workaround: copying tutorial content into the repo?
