### ISSUE TITLE
UFix64/Fix64 shows up as null in account state

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-playground#34]
## 🐞 Bug Report

UFix64/Fix64 values show up as `null` in account state

For example:

```
{
  "balance": null
}
```

## What is the severity of this bug?

**Important:** * We have to do this before we ship, but it can wait until the next sprint (product or feature won't function without it, but it's not blocking us or users right now). Team should do this in the next sprint.

## Reproduction steps

Steps to reproduce the behaviour:

1. Deploy the fungible token contract and save a vault to an account
1. See `null` instead of fixed point number in "Resources" list

- [x] I followed these steps and was able to reproduce the issue

## Expected behaviour

Fixed point numbers should be rendered properly, probably like in JSON-Cadence encoding

## Screenshots

<img width="687" alt="Screen Shot 2020-04-15 at 8 15 25 AM" src="https://user-images.githubusercontent.com/51661/79354466-4b135e00-7ef1-11ea-9b7b-f16e268f7e88.png">

**Comment by turbolent** [comment]
Verified working

```swift
pub contract Test {

    init() {
        self.account.save(1.23, to: /storage/num)
    }
}
```

shows 

```json
{
  "type": "UFix64",
  "value": "1.23000000"
}
```

and

```swift
pub contract Test {

    init() {
        self.account.save(-1.23, to: /storage/num)
    }
}
```

shows

```json
{
  "type": "Fix64",
  "value": "-1.23000000"
}
```
