### ISSUE TITLE
Staging testing and fixing found issues

### ISSUE THREAD

**Issue by devbugging** [onflow/flow-playground#342]
Test staging deployment and describe any issues found in the comments, as well as link any bugfixes PR to this issue.

**Comment by alse** [comment]
- Random 504 timeouts on deploy/save
- “Error: GraphQL error: panic: runtime error: invalid memory address or nil pointer dereference” errors on deploy
- The get project network request that runs after a code redeploy doesn’t include the latest deployed code
- When refreshing the page, the deployed code for some contracts is missing. It shows up again after a second refresh

**Comment by devbugging** [comment]
- Random 504 timeouts on deploy/save
This I believe has something to do with random db disconnects, I've asked SRE about it but they didn't have any logs. We should inspect further why this happens.

- “Error: GraphQL error: panic: runtime error: invalid memory address or nil pointer dereference” errors on deploy
This one is documented in one of the BE issues. 

- The get project network request that runs after a code redeploy doesn’t include the latest deployed code
Is the request confirmed to be sent after the deploy contract is finished? If that's the case we have to check into this as well.

- When refreshing the page, the deployed code for some contracts is missing. It shows up again after a second refresh
This might have to do something with requests going to different replicas. But this should have been fixed by now. Were you able to reproduce this recently?

**Comment by DylanTinianov** [comment]
- Sometimes clicking deploy for the first time says deployed under results but doesn’t show under Accounts.
- Sending default Transaction “hello world” signed by account 1, then again signed by account 2 is not executing but stuck waiting indefinitely

**Comment by devbugging** [comment]
_- Keep seeing “Response: 404 Client Error” in the logs when just clicking on different accounts
This one should be removed. It's related to k8s checks_

**Comment by MrDSGC** [comment]
[FIXED]  Account storage is not reflected after transaction is executed
 recreated by:
1.  deploy "HelloWorld" contract from https://play.onflow.org/b70199ae-6488-4e58-ae58-9f4ffecbd66a?type=tx&id=3e10cb8b-2129-4c3c-ac4b-5a238e511ad1&storage=none to staging playground account
2. Send "Create Hello" transaction from above tutorial.
3. check signer account storage (expect resource, actual empty)
4. refresh page to see expected resource

![image](https://user-images.githubusercontent.com/23225108/193154501-349b90a7-9094-4141-86b3-28806a91ec31.png)

**Comment by MrDSGC** [comment]
[FIXED] New Scripts & Transaction templates are not reflected in file explorer until after refresh


[NOT FIXED/ is this an issue?] console warnings after sending the request
![image](https://user-images.githubusercontent.com/23225108/193155066-9d38d414-2e90-44ea-a444-9c87e9487f24.png)

**Comment by MrDSGC** [comment]
Not sure if this is expected, but the copy snippet button for contract/script/transactions saves a script tag to the clipboard for the code

`<script src="https://playground.staging.flow.com/embed?project=94e16602-e06c-4f77-90c0-aef41276c63e&type=transaction&id=413cc8d2-8de4-4a12-a393-a1505ba6fe6b"></script>`

![image](https://user-images.githubusercontent.com/23225108/193155520-7803f925-c3af-421d-b037-6cee5f5f2698.png)

**Comment by alse** [comment]
@MrDSGC @DylanTinianov the scripts and transactions issues are fixed in #367

**Comment by devbugging** [comment]
@alse going over tutorials I've noticed when you want to add multiple transactions sometimes the request to add a new transaction file takes longer so you click a couple of times and it then creates a bunch of them. Could we look into disabling that button until the request finishes? 
Even better could be to just add an item as soon as you click and do a request async in the background, but if this takes too much work then first approach is good enough.

Same for scripts.

**Comment by devbugging** [comment]
@MrDSGC https://developers.flow.com/cadence/tutorial/06-fungible-tokens#transfer-tokens-to-another-user in the window above with code:
```
post {
// Check that the capabilities were created correctly
// by getting the public capability and checking
// that it points to a valid `Vault` object
// that implements the `Receiver` interface
getAccount(0x01).getCapability(/public/CadenceFungibleTokenTutorialReceiver)
                .check<&ExampleToken.Vault{ExampleToken.Receiver}>():
                "Vault Receiver Reference was not created correctly"
}
```

It doesn't match the tutorial content. Why is that?

**Comment by devbugging** [comment]
Another thing I found during testing is wrong log, when you execute one transaction:
```
"30 tokens minted and deposited to account 0x07"
```
 
@DylanTinianov I will assign you to fix it. flow-playground-api issue: 87

**Comment by MrDSGC** [comment]
> @MrDSGC https://developers.flow.com/cadence/tutorial/06-fungible-tokens#transfer-tokens-to-another-user in the window above with code:
> 
> ```
> post {
> // Check that the capabilities were created correctly
> // by getting the public capability and checking
> // that it points to a valid `Vault` object
> // that implements the `Receiver` interface
> getAccount(0x01).getCapability(/public/CadenceFungibleTokenTutorialReceiver)
>                 .check<&ExampleToken.Vault{ExampleToken.Receiver}>():
>                 "Vault Receiver Reference was not created correctly"
> }
> ```
> 
> It doesn't match the tutorial content. Why is that?

looks like the code block is wrong since the instructions say to use 0x02. i created a pr to fix that https://github.com/onflow/cadence/pull/2020

**Comment by alse** [comment]
> @alse going over tutorials I've noticed when you want to add multiple transactions sometimes the request to add a new transaction file takes longer so you click a couple of times and it then creates a bunch of them. Could we look into disabling that button until the request finishes? Even better could be to just add an item as soon as you click and do a request async in the background, but if this takes too much work then first approach is good enough.
> 
> Same for scripts.

I disabled the buttons in #374 and we should use optimistic ui updates when switching to Apollo 3
