### ISSUE TITLE
Duplicate project user flow

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#348]
- implement user workflow for duplicating a project in playground v2
- duplicate formerly known as `Forking` in v1
- CTA accessed through right clicking project list item

**Comment by MrDSGC** [comment]
- sync with dylan on playground API endpoint for duplicate/forking project
- sync on UI requirements for duplicate project flow

**Comment by fotescodev** [comment]
@fotescodev to break it down, align with design, update description

**Comment by bthaile** [comment]
This functionality works. The user will get a shared link and "save" the project. The saved project gets a new project id and shows up in the user's project list. 
closing
