### ISSUE TITLE
User authentication without cookies

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-playground#35]
**Is your feature request related to a problem? Please describe.**

Currently the playground is not usable in browsers with cookies disabled. This includes private browsing modes (i.e. Chrome Incognito). 

**Describe the solution you'd like**

It would be ideal to have a user authentication mechanism that preserves the following:

- Does not require user signup (no email and password)
- Does not require the use of cookies

We should investigate ways to preserve the "authless" experience of the playground while extending support for additional browser configurations.

**Comment by devbugging** [comment]
V2 is usable in incognito, which is the biggest concern with the issue, so closing.
