### ISSUE TITLE
Edit project name user flow

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#350]
Is your feature request related to a problem? Please describe.
Designs show user input in top nav to name personal projects

Describe the solution you'd like
- implement text input to topnav for editing project names
- defaulted to "Untitled  Project" for personal projects 
- send request on enter

**Comment by devbugging** [comment]
@MrDSGC please define this task according to the template.

**Comment by MrDSGC** [comment]
ETA 11/10

**Comment by MrDSGC** [comment]
completed
