### ISSUE TITLE
Editor file explorer styling

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#356]
Is your feature request related to a problem? Please describe.
Redesigned playground editor has a different styling palette than the current iteration. The file explorer components require styling updated to match the designs.

Describe the solution you'd like
- implement css styling for Editor file explorer components to match 
- icons and buttons are updated to match designs
- Editor file explorer has "collapse" CTA and button per designs
- Editor components organized under high level Editor directory

**Comment by devbugging** [comment]
@MrDSGC please define this task according to the template.

**Comment by MrDSGC** [comment]
ETA 10/26
