### ISSUE TITLE
Templates with redundant numbering

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-playground#36]
Originally reported by @mrbrianhobo 

Currently, there is redundant numbering with the templates that are created. 

How to replicate:
1. Create a new template after default (i.e. `Transaction 2`)
2. Delete template before the newly created template (i.e `Transaction 1`)
3. Create a new template (i.e. new template is numbered `Transaction 2`)

There are now 2 templates named `Transaction 2`

**Comment by MaxStalker** [comment]
Instead of tracking the number, we can create a transaction with "Transaction" name, we already have a mutator, which lets us update the name of the script. We just need to update the code slightly to read it properly.

**Comment by MaxStalker** [comment]
Fixed together with displaying title stored by owner

**Comment by psiemens** [comment]
@MaxStalker Nice! Feel free to tag me on the PR
