### ISSUE TITLE
Topnav

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#361]
Is your feature request related to a problem? Please describe.
v2 Playground mvp needs high level components to be correctly styled

Describe the solution you'd like
- implement css styling on high level components to match designs
- refactor styling implementation to use theme-ui
- add icons to match designs
- implement "saved" timestamp feature on top navbar (extracted to #385)
- refactor component files to reflect high level components. TopNav/ Left Sidebar (see https://github.com/onflow/flow-playground/issues/377)

- [x] #349

**Comment by devbugging** [comment]
@alse add missing tasks

**Comment by MrDSGC** [comment]
completed
