### ISSUE TITLE
Display Cadence version number in the UI

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-playground#37]
**Is your feature request related to a problem? Please describe.**

Currently there is no way to know which version of Cadence is provided by the playground.

**Describe the solution you'd like**

I would like to see the current Cadence version displayed somewhere in the playground UI, ideally near the code editor pane.

**Comment by MaxStalker** [comment]
Hey, @psiemens 👋
I see that we can get it here:
https://github.com/onflow/cadence/blob/8287bb804509859fa5cb2b054d23c0bff841e02e/version.go#L24

Shall I create another controller (feels a bit like overkill) for this one? 🤔
Or `HandleFunc` on a route will be enough?
