### ISSUE TITLE
[TDEBT] Playground components directory reoganization

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#377]
**Is your feature request related to a problem? Please describe.**
The flat file structure of the current playground is disorganized and difficult to parse.
current iteration: https://github.com/onflow/flow-playground/tree/staging/src/components

**Describe the solution you'd like**
The playground component directory organized by high level components. each component will be a directory in the root components directory and contain sub components within them. shared components can be in the root directory

High level components:
- Top nav
Share Button
Project Title Input
Open Tutorial Button
Open Project Button
 
- Left sidebar
Project List
Create Project Button

- Right sidebar
Templates List
Tutorials List
Tutorials Flow

- Editor
Monaco Editor
Result Bottom Bar
Control Panel
Arguments 

**Additional context**

**Comment by devbugging** [comment]
@MrDSGC please move this into subtasks

**Comment by MrDSGC** [comment]
dupe
