### ISSUE TITLE
Breaking down bulky files.

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#382]
**Is your feature request related to a problem? Please describe.**
Some files are fairly large and difficult to parse for incoming developers

**Describe the solution you'd like**
- audit the repo for large files and break them down to smaller lines where it makes sense
- some files to get started with:
https://github.com/onflow/flow-playground/blob/staging/src/providers/Project/projectMutator.ts

**Comment by bthaile** [comment]
closing, standard dev task when in code base
