### ISSUE TITLE
Import projects from GitHub repo and/or local

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-playground#397]
**Is your feature request related to a problem? Please describe.**
It would be great if I could quickly interact with a project I find in GitHub without needing to pull it into my local environment. Not only does Playground provide storage visualization, it's also much easier and intuitive to deploy and run transactions and scripts than a local environment. 

**Describe the solution you'd like**
I'd like an option in Playground to enter the repo url, and have contracts, transactions and scripts directories imported to my project. From there I can deploy the contracts and interact with them via the UI.

**Describe alternatives you've considered**
Alternatively, we could allow users to import projects from their local directory, uploading from their local project's root folder.

On that note, enabling localhost connection would allow users to easily deploy contracts to the Playground's emulator environment and visually inspect account storage. However, this approach is getting out of scope of this feature request, and edging into being a fully fledged in-browser IDE.

**Additional context**
Add any other context or screenshots about the featu

**Comment by devbugging** [comment]
Closing this as it's part of the scope of guided tutorials which are planned.
