### ISSUE TITLE
Deleting a transaction/script template should go to the last created template

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-playground#40]
Originally reported by @mrbrianhobo

> Currently, when a template is deleted, the app navigates to the Contract script. It would be more intuitive if the app navigates to the last created template of the type that was deleted (Transaction/Script) since there will always be at least 1 template of each type.

**Comment by MaxStalker** [comment]
I made it to reset to first one in a list of deleted types. Cause tracking which one was the last one would lead to inconsistent behavior.

**Comment by 10thfloor** [comment]
Fixed!
