### ISSUE TITLE
Signer Panel (scripts and contracts)

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#404]
When the user is editing a script or contract:

 - only one signer can be selected

### Questions:

**How to handle if no signers are selected?**

One signer will be always selected by default.  As a rule, the first account` 0x01` will be the **default** selected account.   If a user selects another account, the previous selection will be disabled, that way only one account can be selected at a time:

![Image](https://user-images.githubusercontent.com/44682521/200351805-4ae27fe8-a84b-4578-8a12-6a780d6a3722.png)

State change of the selected account (displayed on the top):

![Image](https://user-images.githubusercontent.com/44682521/200351966-2ef8fc86-3583-485e-a3c2-6af62489f01a.png)

How to handle if more than one signer is selected?
Do we display an error?

### Design
This design is generic and needs to above questions answered
https://www.figma.com/file/G7Z28scDlkNFvgDyR2nSnq/Playground-Library-%7C-Components-(External)?node-id=298%3A117977

![image](https://user-images.githubusercontent.com/3970376/200037614-45af4fef-6064-4120-b6a8-2b41e2a46c74.png)

**Comment by MrDSGC** [comment]
completed
