### ISSUE TITLE
Signer Panel (transactions)

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#405]
When user is editing a Transaction the user needs to have a correct number of signatories selected.  

**Happy Path 👍**

🔹Single Signer Experience

One signer will be always selected by default - think radio button style 🔘

As a rule, the first account `0x01` will be the account selected "by default".   If a user selects another account they can do so, and the previous selection will be unselected, that way only **one account can be selected at a time** (see below):

![image](https://user-images.githubusercontent.com/44682521/200364752-5f34ddb6-e182-4bdd-8387-183942b24a19.png)

Also the top message will change from `Default` to `1 Signer Selected`:
![image](https://user-images.githubusercontent.com/44682521/200364974-56b655fb-812d-4853-8f0a-b8384117368f.png)

🔹Multiple Signer Experience

For multiple signers per transaction, the user will be guided to select additional signers - think a checkbox style ☑️

If less than the required amount of signers are selected, the Send button will be greyed out, and an orange circle with appear on top with the current amount selected:

![image](https://user-images.githubusercontent.com/44682521/200367360-8a4450c8-7057-4016-9a5a-e26710ca3338.png)

**Assumptions**
- The playground backend knows exactly how many signers are required for each transaction to be executed. 
- The system remembers the signer choice for each transaction

### Questions:

**What if user has too many signers selected?**

Two cases:

**_1. A single signer is required_**

One signer will be always selected by default. The user can only choose one signer at a time. There is no way to unselect all signers.

**_2. More than one signer is required_**
The user is able to choose only the proper amount of signers. The signer has to be unselected to choose another signer.

**What if user has less than needed signers selected?**

The Send / Deploy button will be greyed out: 
![image](https://user-images.githubusercontent.com/44682521/200369192-ced3565f-5229-4ef0-b273-13ab0f674b68.png)

What errors to display and where?

For now, to keep it simple use the number of errors inside the signer panel:
![image](https://user-images.githubusercontent.com/44682521/200381148-d4eaa28e-392c-4529-82a4-9963f475c0e6.png)

Notes:
  ### Transactions:
  - show header message when more signers are needed.
    - `2 of 3 signers` 
  - remove error in this case

### Design

for any additional questions refer to: https://www.figma.com/file/51JJzKlDh2O1nhZNuwzm3v/Playground-Hi-Fi%E2%80%99s-(Internal)?node-id=6%3A139678

signer panel states
https://www.figma.com/file/G7Z28scDlkNFvgDyR2nSnq/Playground-Library-%7C-Components-(External)?node-id=298%3A117977

User editing transaction
https://www.figma.com/file/G7Z28scDlkNFvgDyR2nSnq/Playground-Library-%7C-Components-(External)?node-id=298%3A125484

**Comment by MrDSGC** [comment]
completed
