### ISSUE TITLE
Theme style organization

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#407]
Organize styling for faster development. Need to:

 - figure out theme style naming convention
 - decide how to use style naming to support themes (light, dark, ...)
 - massage existing theme usage to conform to new direction

This effort will speed up development cuz it standardizes component styling.

**Comment by devbugging** [comment]
@bthaile is this still relevant?

**Comment by FidalMathew** [comment]
@bthaile is this issue still relevant? It would be an excellent opportunity to work on it.
