### ISSUE TITLE
Web vitals for Playground

### ISSUE THREAD

**Issue by devbugging** [onflow/flow-playground#408]
follow the instructions [here](https://web.dev/vitals-ga4/#measure) to add the [web-vitals library](https://github.com/GoogleChrome/web-vitals)

- [ ] Add to the current front end (Playground V1)
- [ ] Add to the V2

communication in slack #tmp-playground-web-vitals

**Comment by devbugging** [comment]
Here's the support channel https://dapperlabs.slack.com/archives/C04BWHL0SAJ

**Comment by MrDSGC** [comment]
completed
