### ISSUE TITLE
Create Delete Project confirmation modal

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#413]
Extract modal from ExportPopup and style. Make generic `confirmation` modal.

https://www.figma.com/file/51JJzKlDh2O1nhZNuwzm3v/Playground-Hi-Fi%E2%80%99s-(Internal)?node-id=8%3A56182

![image](https://user-images.githubusercontent.com/3970376/200972054-93d1ef27-b14b-48b4-bed0-69003839cf71.png)

**Comment by MrDSGC** [comment]
completed
