### ISSUE TITLE
Create Delete Project in context menu

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#414]
design
https://www.figma.com/file/51JJzKlDh2O1nhZNuwzm3v/Playground-Hi-Fi%E2%80%99s-(Internal)?node-id=8%3A47531

Need to add top `...` menu button
then add two options

 - Delete Project
 
Ignore duplicate for now 
![image](https://user-images.githubusercontent.com/3970376/200916736-c77ace8c-2a16-452f-acb3-5bece5bac27a.png)

**Comment by MrDSGC** [comment]
completed
