### ISSUE TITLE
[EPIC] Playground Error Experience

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#421]
The Playground 2.0 error experience can be broken into three distinct categories:

1. Code syntax errors (in editor)
   - Signer widget shows number of errors
   - Error details are in Errors tab
  
2. Execution Log errors
   - Log tab

3. Application errors
   - Toast component

See Deploy Contract with Errors section of the Design: https://www.figma.com/file/51JJzKlDh2O1nhZNuwzm3v/Playground-Hi-Fi%E2%80%99s-(Internal)?node-id=8%3A47533

![Image](https://user-images.githubusercontent.com/44682521/201351570-f0c37096-c2cc-4ae3-b387-94980ad9d42a.png)

- [x] #422
- [x] #423
- [x] #424
- [x] #517

**Comment by bthaile** [comment]
This epic has been completed, closing
