### ISSUE TITLE
As a developer I want to know if an execution error has occurred

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#423]
### Description

As a developer I want to know if an execution error has occurred after a Cadence contract has been deployed or Transaction executed.

Execution errors show are not part of the "pre-build" syntax errors, and are displayed in the Logs tab:

![Image](https://user-images.githubusercontent.com/44682521/201366340-f6f0809d-1d8f-472c-a464-f82ea74487ec.png)

### Acceptance Criteria

- [ ] Simulate a test error that would be displayed as an execution error inside the `Logs` panel

**Comment by fotescodev** [comment]
Need to discuss this ticket in detail with @sideninja and @MrDSGC

**Comment by bthaile** [comment]
closing, execution errors are shown in logs tab.
