### ISSUE TITLE
Project list with Real Data

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#427]
Replace mock project data with real data from backend. 

User flow is:
First arrives there is a default project. 
Cookie is placed that uniquely identifies the user
User can have a total of 10 projects
When user returns the cookie is used to uniquely identify their projects (need to investigate this link to backend)

Cookie is set. 
 - [x] - `Do we need a cookie notification to user?` (exists)
 - `Is there a fallback if user doesn't allow cookies?` browser thumbprint?

Backend query:
Query `projectList` to get the user's projects. 
```query() {
  projectList() {
    projects {
      id
      title
      # Whatever else you want here
    }
  }
}```

**Comment by MrDSGC** [comment]
completed
