### ISSUE TITLE
Don't allow user to delete last project

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#428]
Create generic Informational Modal 
 - change confirmation modal to a be more generic to pass in the buttons
 - create new informational modal to use the confirmation modal and only pass in one button `ok`

use the new modal to tell the user they can't delete the last project. They have to create another blank project in order to delete the active project (last one).

https://www.figma.com/file/51JJzKlDh2O1nhZNuwzm3v/Playground-Hi-Fi%E2%80%99s-(Internal)?node-id=8%3A47531

**Comment by MrDSGC** [comment]
completed
