### ISSUE TITLE
Tell user they have reached max projects

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#430]
When user clicks to add project,

Display Informational modal tell user they have reached project limit of 10.

Questions:
The user can create new projects a few ways, 
1. duplicate existing.
2. forking someone someone else project.
3. creating a new project. 
4. saving default project (doesn't hit hard limit)

Currently we have a hard limit of 10 projects. Do we block all these creation methods if they already have 10 projects?

Where do we enforce this hard limit? Seems like it's a limit per web browser since we don't have accounts per username.

**Comment by fotescodev** [comment]
@sideninja @DylanTinianov the enforcement would happen client side correct?

**Comment by devbugging** [comment]
Yes, but still have to have a backend validation.
