### ISSUE TITLE
[EPIC] Playground Project Experience

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#432]
As a developer I would like to create multiple Cadence projects and keep track of them. 

Designs: https://www.figma.com/file/51JJzKlDh2O1nhZNuwzm3v/Playground-Hi-Fi%E2%80%99s-(Internal)?node-id=137%3A185743

**Workflow Description**

1. **Starting workflow.** A first time user opens the playground with a default project pre-populated, let's call it project `Untitled Project`:

![Image](https://user-images.githubusercontent.com/44682521/203390847-f43b5560-9d91-4cce-ad73-c020fbb458cf.png)

❗Things to notice:
- This project has not been saved yet which means that the `Share` button is not enabled yet. Instead the user sees a `Save` button:

![Image](https://user-images.githubusercontent.com/44682521/203391750-86f10c7b-4068-4288-ab3b-5ce2afa52bd5.png)

- Once the user clicks on `Save` and goes through the process of saving the project: 

1. The `Save` button turns into `Share` button.

2. Automatic project saving has been enabled that shows `Saved at`

3. Project appears under the Projects Section inside the Left Sidebar:

![Image](https://user-images.githubusercontent.com/44682521/203403413-704bcfcc-01f3-4b09-965b-5eb4718d64b1.png)

**Questions:**
_Save button should not turn in to share button (confusing)_ 

If the user uses the save button only to save the project initially, does it make sense to have the Save button all the time? @bthaile thoughts?
@fotescodev  save button turns into the time label when the project was saved, save button does go away and replaced with save time. These two components are related so makes sense.

_Are we removing the "+" button next to "Projects" button?_

Yes, we are removing the "+" button as it's redundant.

 _Is there any reason the user would want to collapse the project list?_
 
Given that we have only 10 Projects limit, at this point we can remove the behavior. However, in the future, between Tutorials and Projects the user may find it useful.

2. **Multiple Projects Workflow (10 MAX)**

- When the user has multiple local projects saved, these cards are listed down the drawer, with a New Project button at the bottom.

- Selected project shown with a blue border.

- User can tap on chevrons below PROJECTS to collapse list.

- 10 Projects is the hard limit at the moment

![Image](https://user-images.githubusercontent.com/44682521/203403495-a40d652b-fe83-4ac4-b175-ed30b6357ce5.png)

Current set of User Stories is:

- [x] #430 
- [x] #429 
- [x] #449 
- [x] #428 
- [x] #347 
- [x] #414 
- [x] #460 
- [x] #461

**Comment by MrDSGC** [comment]
done
