### ISSUE TITLE
Error: "could not find document error"

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#437]
Error originating from `getParameters` in src/components/CadenceEditor/ControlPanel/index.tsx

![Image](https://user-images.githubusercontent.com/3970376/202507811-48492788-4160-4ab3-975e-e01ef9e2b3f4.png)

Need to determine if a valid error and address.

**Comment by MrDSGC** [comment]
- reproduced error by deleting templates and switching between projects (also deleting
- editor uris are "generated" as new templates are opened, previously opened templates will use original uri.
- error stems from editor sending bad URI to cadence server (hypothesis: uri for deleted template being sent to cadence server)
- error goes away for 1 project on refresh, resurfaces when switching to a different project
- does not affect user flow as far as we know

**Comment by justinbarry** [comment]
Stale.
