### ISSUE TITLE
Tell user they are going to lose changes

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#449]
In a few scenarios user will lose changes if they have not saved their project.

Since we are not auto saving a new project, the user has to manually save. The user can create a project:
 - click "+" button or "create new project"
 - select a tutorial
 - load a shared project link and change a file

If there are local changes the user will lose those changes if they:
 - [x] refresh browser
 - [x] select a different project

We need to put up a modal to inform them they are going to lose changes.

**Comment by bthaile** [comment]
verified that user gets a prompt if they have unsaved changes and navigates away.

**Comment by MrDSGC** [comment]
done
