### ISSUE TITLE
Running list of UX and Functional bugs

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#465]
As we approach the MVP Release, we have identified the following UX, functional issues that need to be polished before the release:

Functional Issues / Bugs:
- [x] #472 
- [x] #485
- [x] #490
- [x] #491
- [x] #492
- [x] #493
- [x] #494

UX Issues:
- [x] #467
- [x] #468
- [x] #469 
- [x] #470
- [x] #471
- [x] #479
- [x] #482
- [x] #484 
- [x] #453

**Comment by bthaile** [comment]
all items addressed, closing
