### ISSUE TITLE
Initial Load Optimization

### ISSUE THREAD

**Issue by devbugging** [onflow/flow-playground#466]
The first load of playground is slow due to LangaugeServer dependency being loaded (~10MB in size). Right now that is being loaded concurrently so it doesn't block the client but there might be some further speed optimizations we could do as for example using HTTP/3 with QUIC and using CDN.

**Comment by justinbarry** [comment]
@sideninja is this still valid?

**Comment by devbugging** [comment]
Yes, it is. We need to put Cloudflare in front of Playground or any other CDN service, but I suggest Cloudflare as it also acts as WAF. 
cc @bthaile
