### ISSUE TITLE
Display Line Numbers for Runtime Error

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow-playground#47]
Context:
When a runtime error occurs we need to display the line number which the error occurs. 

Would also be nice to display of error position in the log window, would be great if we can implement “jump to”, so we could put a cursor to an actual position of error

**Comment by MaxStalker** [comment]
Quick search proved, that server returns us just information about error, without any indication on what line it occurred, thus it's impossible to do it atm.

@psiemens @turbolent do you think it's possible to add line number information to error? 🤔

**Comment by 10thfloor** [comment]
This is more of a BE issue.

**Comment by MaxStalker** [comment]
I found a solution to make this one work on FE for syntax errors :)
