### ISSUE TITLE
Save error from backend

### ISSUE THREAD

**Issue by bthaile** [onflow/flow-playground#473]
User comes to site and tries to save a new project
![image](https://user-images.githubusercontent.com/3970376/204616622-ffc3943f-ac82-4541-a212-cf7a67f10c74.png)

![image](https://user-images.githubusercontent.com/3970376/204616558-bd4b10e0-061b-4d4b-bd2c-4b78f921d1fe.png)

Work around:
Clear application data allows the user to save a project.

**Comment by justinbarry** [comment]
Stale.
