### ISSUE TITLE
Align the contents of the Contract menu

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#479]
When the user clicks on the menu:
<img width="208" alt="Screen Shot 2022-11-30 at 1 35 40 PM" src="https://user-images.githubusercontent.com/44682521/204881417-996aa46b-3e59-461c-a126-90c5e5af4056.png">

The contents of the menu are misaligned:
<img width="200" alt="Screen Shot 2022-11-30 at 1 28 05 PM" src="https://user-images.githubusercontent.com/44682521/204881519-c616383d-6e2e-433f-9997-56df0f11d70b.png">

**Comment by bthaile** [comment]
fixed, closing
