### ISSUE TITLE
Hide the thick margin from the top of the editor view and make it look according to the design

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#482]
Currently we are displaying a margin on top of the editor view that does not exist in the design and looks rather clunky: 

<img width="1859" alt="Screen Shot 2022-11-30 at 2 20 58 PM" src="https://user-images.githubusercontent.com/44682521/204891962-4cd19a70-1d3e-46d0-8d05-8d1ebe4541b8.png">

Two tasks:

- Hide the top margin
- Align the Contract name label with the code line numbers

**Comment by bthaile** [comment]
Styling changes have been made to get ready for release. closing this
![image](https://user-images.githubusercontent.com/3970376/230655834-4162fe56-ef62-4249-a6f4-cb6df25b433e.png)
