### ISSUE TITLE
Updated the Avatar Generation API

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#489]
Currently the image is hardcoded. 

![Image](https://user-images.githubusercontent.com/44682521/205324504-47bf309c-bdc9-4381-8910-9e23b1f61f31.png)

**Comment by fotescodev** [comment]
@MrDSGC is there anything pending on this task? Any dependencies we are waiting for?

**Comment by MrDSGC** [comment]
> @MrDSGC is there anything pending on this task? Any dependencies we are waiting for?

depends on where we landed on this discussion https://dapperlabs.slack.com/archives/C03UWGN8M0Q/p1667933138083639

**Comment by bthaile** [comment]
This has been addressed, stored profile pics in code
