### ISSUE TITLE
Issue on Chrome: GraphQL error - failed to load user from session, record not found

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#490]
This happens on Chrome (Incognito mode as well). Reseted cache and deleted application data. Firefox appears to be working fine. 

![2022-12-02 10 36 16](https://user-images.githubusercontent.com/44682521/205330381-da6139e2-a438-49cf-9cd1-c4a10f679006.gif)

**Comment by MrDSGC** [comment]
CONTEXT
- unable to recreate at the moment but ive ran into the issue before (@MrDSGC )
- chrome only issue. 
- cookie name = `flow-playground` 
- fork/save button behavior in v1 is linked to session/cookie id: https://github.com/onflow/flow-playground/blob/production/RUNBOOK.md#how-it-works
- save/share button https://github.com/onflow/flow-playground/blob/production/src/containers/Editor/layout.tsx#L229

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/23225108/207494739-10c7e1bb-f44f-4b4b-a32b-68b4ea7a30fc.png">
