### ISSUE TITLE
Delete final project while you have unsaved project open does not work but no modal message

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#491]

**Comment by bthaile** [comment]
Is this now fixed?
Ignore styling of context menu that is fixed on a PR in review.

![Image](https://user-images.githubusercontent.com/3970376/205707793-e63200a3-d590-47a3-bbb5-68cb00fffe6e.gif)

**Comment by fotescodev** [comment]
@bthaile yes, fixed
