### ISSUE TITLE
Playground Project state inconsistency

### ISSUE THREAD

**Issue by MrDSGC** [onflow/flow-playground#501]
**Describe the bug**
When user actions are made, changes/response are not reflected to the user immediately.

- user actions include but not limited to: updating project name, opening user account storage, opening project file, switching projects, etc
- playground usually behaves as expected on the 1st few requests. then UI becomes "1 request" behind 
- changes are usually observed after a page refresh
- this behavior was found in the v1 playground as well. was fixed by alex with 

**To Reproduce**
Complete a user request and observe the response (or lack of)
Refresh page to confirm the changes
Some common user actions:
- delete a file in a project and select different files/switch projects (warning error should show in console)
- change a name of project
- select account from fileexplorer to open account storage view, switch between accounts

**Additional context**

Possible reasons:
- apollo local storage cache out of sync with project user sees
- cadence server memory out of sync with project user sees
- component hook state not being updated on user request
- further investigation required

One way to replicate the state issue, play with deploying a contract to 0x1 and notice how the storage account is being displayed:

![Image](https://user-images.githubusercontent.com/44682521/205988381-2bc341c8-f9be-4da5-ac7a-a40cc65afbfb.gif)

And we have double-checked it with @sideninja, it's not an API issue. The API consistently shows that 0x01 has the contract deployed to its storage.

Tickets associated with this issue
 - [x] https://github.com/onflow/flow-playground/issues/503
 - [x] https://github.com/onflow/flow-playground/issues/515
 - [x] https://github.com/onflow/flow-playground/issues/508

**Comment by fotescodev** [comment]
@sideninja @gpavlov2016 this risk was surfaced yesterday. Let's review it and come up with a plan of action. This will most likely push the "MVP" release date.

**Comment by MrDSGC** [comment]
fixed
