### ISSUE TITLE
Deployment and hosting of V2 as a separate Beta (standalone) application

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#504]
URL: play.beta.onflow.org

**Comment by fotescodev** [comment]
@sideninja if we decide to use the staging env, what do we need to change the domain from play.staging.onflow.org to play.beta.onflow.org ?

**Comment by DylanTinianov** [comment]
@fotescodev I think we would just have to add this domain to the FE in Vercel and also add it to the allowed origins on the BE deployment.

**Comment by fotescodev** [comment]
@DylanTinianov sounds like a plan! Let's do it earlier than later.

**Comment by DylanTinianov** [comment]
Added play.beta.onflow.org to allowed origins for staging backend

**Comment by DylanTinianov** [comment]
Created an SRE ticket for creating a new namespace, node pool, domain, and postgres database for a new beta deployment on our production environment. We can then target this deployment in the k8 manifests and deploy our v2 beta.

**Comment by DylanTinianov** [comment]
Released https://beta.play.flow.com
