### ISSUE TITLE
Update Google Analytics to GA4

### ISSUE THREAD

**Issue by gpavlov2016** [onflow/flow-playground#509]
Universal Analytics (the version that the website is currently using) is getting deprecated in July 2023. In addition it's not compatible with data team ingestion pipelines.
The code should be updated to use GA4. Here is a [link](https://analytics.google.com/analytics/web/#/a156047066w225522445p213554995/admin/ga4-setup-assistant) to help upgrade to GA4 for that specific project, and here is a [general guide](https://support.google.com/analytics/answer/10759417?hl=en) on upgrading to GA4.
It is up to the developer to decide whether to use a new GA project or an existing one (no events yet). The existing GA4 project details:
```
flow-developer-playground
(id: 221327396)
```

**Comment by bthaile** [comment]
https://analyticahouse.com/blog/how-to-integrate-google-analytics-4-to-react

@gpavlov2016 
Does anyone have a Google Analytics 4 account. Seems that is needed.
Then whom ever has the Universal Analytics account, they need to create a GA4 property. They can use the GA4 Property Setup Assistant. 

Our playground is already using `ReactGA` lib. So I think playground is good to go. No code changes are needed from what I can tell from documentation.

**Comment by gpavlov2016** [comment]
The GA4 property was connected however the code integration needs to be updated - there is currently no data 
Please use the measurement ID G-GY6BHGBVKN
If using GTM here is the snippet:
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-GY6BHGBVKN"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-GY6BHGBVKN');
</script>
```

**Comment by bthaile** [comment]
updated the vercel configuration env variable to the `G-....` value. Also redeployed production and staging to make sure the new value is used.

**Comment by gpavlov2016** [comment]
Verified on GA - we now have data streaming. Closing the ticket
