### ISSUE TITLE
Playground redeployment issue

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#552]
Much better UI, very poor usage. I'm attempting to test a contract which required FT, NFT, MV contracts plus my own. After adding FT and NFT, updating MV to reference 0x01 or any account for that matter, it can't import from other account. 

Also, the contracts move around the list after attempts to deploy. Redeployment seems to fudge everything. Good effort, unusable result. Look forward to the upgrades

**Comment by DylanTinianov** [comment]
There seems to be a larger issue with language server and imports https://github.com/onflow/flow-playground/issues/556

**Comment by MrDSGC** [comment]
closing duplicate issue 
contracs moving: https://github.com/onflow/flow-playground/issues/529
redeploy issue: https://github.com/onflow/flow-playground/issues/555
