### ISSUE TITLE
Redeploy button shown when deploying to fresh account

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground#555]
**Describe the bug**
Redeploy is shown when deploying to an account without the contract previously deployed.
One simple solution is to always have the button say "Deploy" and just never say "Redeploy". Otherwise we will want to instead check if the account your deploying to has the contract deployed already. 

**To Reproduce**
1. Deploy a contract to 0x01
2. Select a different signer
3. Button should says redeploy

**Expected behavior**
Button should say deploy instead of redeploy

**Comment by bthaile** [comment]
This has been addressed
