### ISSUE TITLE
UFix64.fromString is not working

### ISSUE THREAD

**Issue by hieudo2** [onflow/flow-playground#562]
**Describe the bug**
When I using this code `UFix64.fromString("100.0")`; I got an error on runtime ```value of type `((_ value: Number): UFix64)` has no member `fromString`. unknown member```

**To Reproduce**
1. Go to [beta.play.flow.com](beta.play.flow.com) and create new Script
2. On script body, type this text ``UFix64.fromString("100.0")`
3. View the snip

**Expected behavior**
`UFix64.fromString` can use as normally

**Screenshots**
![image](https://user-images.githubusercontent.com/125846934/220003770-fa3408b6-413b-43e5-bb53-035442ce465f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.0.4 LTS
 - Browser: Brave
 - Version [Version 1.48.164 Chromium: 110.0.5481.100 (Official Build) (64-bit)]

**Comment by bthaile** [comment]
Need to see if upgrading language server will fix this issue.

**Comment by bluesign** [comment]
upgrading LS fixes the issue: https://run.dnz.dev/snippet/c701872ac1f04dae
