### ISSUE TITLE
BUG: Deploying `FungibleToken` + `FlowToken` causes an unknown unexpected error

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-playground#563]
**Describe the bug**

**To Reproduce**
1. Copy the [`FungibleToken`](https://raw.githubusercontent.com/onflow/flow-ft/master/contracts/FungibleToken.cdc) standard interface into account `0x01`.
2. Delete the default implementations for `getViews` and `resolveView` because they are not supported in the playground
3. Deploy to account `0x01`
4. Copy the [`FlowToken`](https://raw.githubusercontent.com/onflow/flow-core-contracts/master/contracts/FlowToken.cdc) definition into account `0x02`
5. Update imports to import `FungibleToken` from `0x01`
6. Try to deploy
7. Error should appear:
8. Console output:
```
Cadence Language Client: called execute command: cadence.server.parseEntryPointArguments
instrument.js:107 Error: GraphQL error: something went wrong, we are looking into the issue
    at new t (bundle.esm.js:63:28)
    at Object.next (bundle.esm.js:1004:53)
    at C (Observable.js:135:18)
    at b (Observable.js:179:3)
    at e.value (Observable.js:235:7)
    at bundle.esm.js:866:75
    at Set.forEach (<anonymous>)
    at Object.next (bundle.esm.js:866:27)
    at C (Observable.js:135:18)
    at b (Observable.js:179:3)
    at e.value (Observable.js:235:7)
    at Object.next (SerializingLink.js:52:71)
    at C (Observable.js:135:18)
    at b (Observable.js:179:3)
    at e.value (Observable.js:235:7)
    at bundle.esm.js:76:26
(anonymous) @ instrument.js:107
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
```

**Expected behavior**
Smart contract should deploy properly

**Screenshots**
![Screen Shot 2023-02-28 at 7 58 55 AM](https://user-images.githubusercontent.com/7407828/221875877-b8586e74-9d5d-49d3-a802-543853cc0929.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version Version 106.0.5249.119
 Other users have reported also presumably with different versions

**Additional context**

**Comment by DylanTinianov** [comment]
We still need to add support for deploying with initialization arguments on Playground. This links to https://github.com/onflow/flow-playground-api/issues/232
