### ISSUE TITLE
Run V1 to V2 migration on backend

### ISSUE THREAD

**Issue by justinbarry** [onflow/flow-playground#573]

**Comment by DylanTinianov** [comment]
Steps
- [ ] Obtain dump of production v1 database
- [ ] Run database migrator locally to convert v1 projects into v2 database
- [ ] Upload new v2 database to staging + deploy latest Playgroundv2 to staging
- [ ] Verify tutorials were migrated successfully
- [ ] Upload v2 database to production + Deploy latest Playgroundv2 to production
