### ISSUE TITLE
Beta playground UI issues

### ISSUE THREAD

**Issue by devbugging** [onflow/flow-playground#579]
- [x] Wrong text color in the top-left burger button
![Screenshot 2023-03-23 at 10 39 11](https://user-images.githubusercontent.com/75445744/227163087-dc622d32-0d6d-447b-af89-a17ca75842f4.png)

- [x] Wrong copy icon top-right IDE corner
![Screenshot 2023-03-23 at 10 42 08](https://user-images.githubusercontent.com/75445744/227163802-0eeab2e3-1002-4a50-a4a8-358fce8b951b.png)

- [x] No border-radius on the IDE window
![Screenshot 2023-03-23 at 10 42 47](https://user-images.githubusercontent.com/75445744/227163911-7867ba8d-ea4a-42aa-bb6d-e722aacce0e1.png)

- [x] Extra visible divider between file name an text editor, which is also draggable for some reason
![Screenshot 2023-03-23 at 10 43 12](https://user-images.githubusercontent.com/75445744/227164137-1ec67cc0-a7d2-4f94-88bb-092c2a2d09e4.png)

- Wrong font-sizes and also an extra gray bar at the bottom of all avatars  
![Screenshot 2023-03-23 at 10 44 24](https://user-images.githubusercontent.com/75445744/227164467-2ef33181-7857-4a55-929a-2a45c7ba8ef4.png)

- Insufficient margin between titles and groups
![Screenshot 2023-03-23 at 10 45 35](https://user-images.githubusercontent.com/75445744/227164704-7b4fd395-281e-4ece-b49b-48ccccd96a10.png)

- Wrong font sizes, colors, and weights 
![Screenshot 2023-03-23 at 10 48 51](https://user-images.githubusercontent.com/75445744/227165594-70b7ca9c-e220-41bf-be7b-c12d06cbc284.png)

- [x] Issue for Error Pane: https://github.com/onflow/flow-playground/issues/581
- Error handling not working properly, the items in the error list don't show the line, it's too vague, and when clicked it should highlight the error or move the cursor to that line at least. The minimal would be to show the error line, otherwise we don't get any information from the list
![Screenshot 2023-03-23 at 10 51 54](https://user-images.githubusercontent.com/75445744/227166485-c72985f1-19f9-465c-8efb-06106ba08455.png)

- [x] Also error handling only shows one error even if multiple syntax errors are present

- addressed in PR: https://github.com/onflow/flow-playground/pull/580
- [x] The error should be clickable to open the error tab at the bottom
![Screenshot 2023-03-23 at 11 11 13](https://user-images.githubusercontent.com/75445744/227171664-51287791-f021-4eb4-828f-118a3ea9f6bb.png)

Existing Issue: https://github.com/onflow/flow-playground/issues/529
- Order of contracts is non-consistent
![Screenshot 2023-03-23 at 11 05 08](https://user-images.githubusercontent.com/75445744/227169976-85c3670b-1400-4296-9ea9-f639d33c1430.png)

addressed in PR: https://github.com/onflow/flow-playground/pull/580
- [x] Long file names mis formatting
![image](https://user-images.githubusercontent.com/3970376/227238061-6ec1614b-51dc-4ac4-a74f-006e9dac7362.png)

**Comment by devbugging** [comment]
Another thing that would be an improvement, would be to not even allow selecting more signers than required, so this wouldn't be possible:
![Screenshot 2023-03-28 at 17 42 07](https://user-images.githubusercontent.com/75445744/228292835-bf8092d3-78d7-4f00-acc0-48fd7eb17838.png)

**Comment by devbugging** [comment]
When creating new files they don't show the correct icon, they show the default file icon (left from the name). 
![Screenshot 2023-03-28 at 17 43 32](https://user-images.githubusercontent.com/75445744/228293163-864345ed-487f-463d-bfc8-43abd13146bf.png)

Also it would feel more natural when creating a new file that it would first ask you for name, and only when you would insert the name and press enter it would create the new file.

**Comment by devbugging** [comment]
The order of files keep changing between refreshes:

![Screenshot 2023-03-28 at 17 45 01](https://user-images.githubusercontent.com/75445744/228293464-bfbf2648-3ade-47a2-9454-2aba79a8afc0.png)

![Screenshot 2023-03-28 at 17 45 20](https://user-images.githubusercontent.com/75445744/228293540-a3edd089-6821-40b8-9a4d-139a380f75fb.png)

**Comment by bthaile** [comment]
All these issues have been addressed. closing
