### ISSUE TITLE
Support Initialization Arguments

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground#596]
**Is your feature request related to a problem? Please describe.**
Currently there is no way for users to pass initialization arguments to contracts

For example, the FlowToken contract takes in AuthAccount:
https://raw.githubusercontent.com/onflow/flow-core-contracts/master/contracts/FlowToken.cdc

**Describe the solution you'd like**
Add UI elements for passing initialization arguments when deploying contracts.

Must be coordinated with https://github.com/onflow/flow-playground-api/issues/232 to define GraphQL schema for deploying with arguments.

**Comment by bluesign** [comment]
AuthAccount cannot be passed as deployment ( initialization ) argument normally. Maybe custom deployment via generated transaction can be good option for advanced use cases.
