### ISSUE TITLE
File deleting functionality is not working

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#612]
For unsaved projects:

**Describe the bug**

**To Reproduce**

![2023-04-03 12 26 46](https://user-images.githubusercontent.com/44682521/229570641-5480e764-f4d0-4f8a-8321-e856ffa41164.gif)

**Expected behavior**
The operation should prompt a confirmation dialogue window and delete the file in question.

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser chrome

**Comment by bthaile** [comment]
There are side effect of letting users change the local-project. Example they might delete files and rename files then save.
If they `create a new project` which uses local-project they will see their pervious changes before they saved the project.

**Comment by fotescodev** [comment]
So if I rename it and save it, I should be able to delete the files in the file list?

**Comment by bthaile** [comment]
There is an existing annoyance with `create new project` doesn't work correctly. This is contributing to `local-project` not looking correctly.  I need to investigate more about changing `local-project` there might be a cache issue.

https://github.com/onflow/flow-playground/issues/613

Currently deletes fail cuz the project is local, that can be changed. I need to fix the local project cache issue.
