### ISSUE TITLE
Continue from last project 

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-playground#622]
**Describe the bug**
Playground should resume last project ( instead of creating a new local one ) 

**To Reproduce**
- go to playground, create a project ( deploy hello world ), clone browser 
- go to playground again, even projects are shown on the projects drawer, it starts a blank new one 

**Expected behavior**
should resume old project 

**Desktop (please complete the following information):**
any

**Additional context**
Because of this, users can easily hit 10 project limit and need to clean up projects

**Comment by bthaile** [comment]
Note, could save current project id to local storage so that project would be loaded when user comes back.

**Comment by bthaile** [comment]
This has been implemented. closing
