### ISSUE TITLE
Add account not working

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-playground#623]
**Describe the bug**
Add account ( + sign next to accounts ) is not working 

**To Reproduce**
- click + next to accounts

**Expected behavior**
should add a new account 

**Desktop (please complete the following information):**
any

**Comment by bthaile** [comment]
@fotescodev  we can prob remove the plus button, it's not active.

![Screenshot 2023-04-04 at 9 56 42 AM](https://user-images.githubusercontent.com/3970376/229833278-3c23b3ce-f51c-45d9-a525-0ed7c37202e8.png)

**Comment by shaununderwood** [comment]
Or, make it add accounts?  If one is using the playground to run some scenarios involving typical production scenarios (ok maybe the playground isnt the best place for that, but...) it becomes difficult/impossible due to the 1 contract 1 account featurette.

**Comment by DylanTinianov** [comment]
The functionality for adding additional accounts was not implemented yet. We are going to remove the button for adding accounts (https://github.com/onflow/flow-playground/issues/632) while we work on resolving other bugs. We will be adding this feature back soon. Apologies  for the inconvenience!

**Comment by bluesign** [comment]
new playground is amazing @DylanTinianov, there is no inconvenience
