### ISSUE TITLE
Maximum number of 10 projects reached, and Error: Loading Projects

### ISSUE THREAD

**Issue by shaununderwood** [onflow/flow-playground#626]
**Describe the bug**
Load up a new page, click save, and gets the above message. Click the projects button and it gives red text saying "Error: Loading Projects"

**To Reproduce**
Load up the default URL https://play.flow.com/local-project hit save

**Expected behavior**
To save and not error

**Screenshots**
![image](https://user-images.githubusercontent.com/1231293/229902705-656f401f-8c4e-4ec3-a376-cfeb6a1e38bf.png)
<img width="478" alt="image" src="https://user-images.githubusercontent.com/1231293/229902762-a53c5ef0-963c-4de2-98ed-37339ca64f3a.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version Version 111.0.5563.146 (Official Build) (x86_64)

**Additional context**
Seems to work in firefox.

**Comment by DylanTinianov** [comment]
From https://github.com/onflow/flow-playground/issues/617:
> To Reproduce
> 
> Steps to reproduce the behavior:
> 
> For me, I only have to go to playground for the error to occur. I'm assuming this is due to previous projects cached in my browser, as I don't have the problem in incognito or other browser windows.
> 
> - MacOS, Chrome

**Comment by shaununderwood** [comment]
I've just checked play.staging.onflow.org and this error doesn't reappear.  

Happy days!

**Comment by bthaile** [comment]
Great to hear the issue has been resolved, closing
