### ISSUE TITLE
Add back link to Cadence Docs?

### ISSUE THREAD

**Issue by shaununderwood** [onflow/flow-playground#627]
**Is your feature request related to a problem? Please describe.**
Complaint: you removed the Cadence docs link

**Describe the solution you'd like**
Add it back, perhaps?

**Describe alternatives you've considered**
Roll back the playground to a version that actually works in Chrome?

**Comment by bthaile** [comment]
Added back link to Cadence docs

![Screenshot 2023-04-07 at 12 57 51 PM](https://user-images.githubusercontent.com/3970376/230655415-b0717caf-6523-4c84-b03b-2ab0c385fb67.png)

**Comment by bthaile** [comment]
done closing
