### ISSUE TITLE
"Showing the errors and logs will help a lot, like in the previous version of Flow Playground

### ISSUE THREAD

**Issue by itscoolsem** [onflow/flow-playground#628]
"Showing the errors and logs will help a lot, like in the previous version of Flow Playground

**Comment by bthaile** [comment]
Are you able to see the `logs` and `errors` tabs at the bottom of the webapp?

![2023-04-05 15 29 18](https://user-images.githubusercontent.com/3970376/230203428-ee73b259-cfe2-4533-a39c-e6eb6d9231fe.gif)

**Comment by itscoolsem** [comment]
I am talking about logs like this: 'log("empty vault created")'. We are not
able to see the logs that we are executing in the log panel anymore.

**Comment by itscoolsem** [comment]
You can see more problems in this video that I created

https://www.loom.com/share/bdab53f2b48148ba908cac3020eba843

**Comment by bthaile** [comment]
@sumitchoudharySEM  Thanks for your video it was very helpful to understand what you are seeing. 
There does appears to be a backend like a slow down we were not seeing earlier this week. Created ticket https://github.com/onflow/flow-playground-api/issues/246 to look at slowdown

Also noticed that the UI isn't giving any indication the code has errors. example imported contracts have not been deployed. 

In this simple example, log statements are getting printed out as expected.
![2023-04-07 11 25 32](https://user-images.githubusercontent.com/3970376/230643516-3080f789-7ba0-4ca0-a586-a559754e3159.gif)

**Comment by itscoolsem** [comment]
Thanks

**Comment by bthaile** [comment]
@sumitchoudharySEM  are you still seeing issues? The backend slowdown has been addressed.

**Comment by bthaile** [comment]
No feedback from user and many improvements have been released. closing
