### ISSUE TITLE
Contract deployment errors

### ISSUE THREAD

**Issue by p29hieu** [onflow/flow-playground#630]
**Describe the bug**
Can't deploy multiple contract in one account.

**To Reproduce**
1. Deploy Contract1 to account 0x01
2. Deploy Contract2 to account 0x02
3. Deploy Contract3 using Contract1 and Contract2 to account 0x02
4. Deploy Contract4 using Contract1, Contract2, Contract3 to account 0x03
5. Got an error
**Expected behavior**
Deploy Contract4 to account 0x03 success. And can remove/redeploy old contracts.

**Screenshots**
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/55887941/230147725-5cf105cd-3d8c-422e-bcc6-e22293abfc89.png">

**Desktop (please complete the following information):**
 - OS: [MacOS 13.3]
 - Browser [Brave]
 - Version [Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (arm64)]

**Comment by DylanTinianov** [comment]
Hey @p29hieu, could you please provide me with a copy of the contract you are having an issue deploying?

**Comment by p29hieu** [comment]
> Hey @p29hieu, could you please provide me with a copy of the contract you are having an issue deploying?

Yes, you can try in [here](https://play.flow.com/f7f717a3-2f51-416d-9ec4-1aed3ffb3bdb?type=contract&id=2fe30463-c399-41c9-a237-3cde959c7118)

**Comment by p29hieu** [comment]
Now when I try it again, It's working.
