### ISSUE TITLE
Stops working and when refreshed the code disappears

### ISSUE THREAD

**Issue by DeeKay02** [onflow/flow-playground#640]
**Describe the bug**
When I'm working in the Playground after some time the deploy functionality stops working and if I refresh all the codes get wiped out and nothing gets saved. I had to start typing again from the start

**To Reproduce**
Use playground and try deploy after idling for some time

**Expected behaviour**
Code stored locally and doesn't get lost when refreshed

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave

**Comment by bthaile** [comment]
At anytime was the project saved? It should auto save if a contract is deployed. 
Or if the save button is clicked. After the project is saved the UI will auto-save any changes.  Reason for this behavior is the backend will only save 10 projects for the user.

Also, do you have any saved projects? Just wondering if your user token was ever saved to api.
![2023-04-10 19 54 44](https://user-images.githubusercontent.com/3970376/231027650-84782f31-5c22-413d-aba0-bfa26326d5b4.gif)

**Comment by bthaile** [comment]
I think this has been addressed when api performance issue was fixed. closing
