### ISSUE TITLE
I couldn't even compile a contract

### ISSUE THREAD

**Issue by Braviti0** [onflow/flow-playground#654]
**Describe the bug**
I couldn't deploy any contract on the site

Oops, There is an Issue!!!
Sorry about this

Issue loading project: "Cannot read properties of undefined (reading 'mutable')"

Click <ok> to go to home page or last loaded project

**To Reproduce**

**Expected behavior**
Oops, There is an Issue!!!
Sorry about this

Issue loading project: "Cannot read properties of undefined (reading 'mutable')"

Click <ok> to go to home page or last loaded project

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WINDOWS 11
 - Browser BRAVE AND CHROME

**Additional context**

**Comment by bthaile** [comment]
Do you happen to know the project id of the project trying to be loaded?

**Comment by bthaile** [comment]
Try again, we released a new backend version.

**Comment by bthaile** [comment]
assuming fixed, user hasn't responded.
