### ISSUE TITLE
[BUG]: Screen goes white when clicking on an account

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-playground#663]
**Describe the bug**
When opening up any existing project, if I immediately click on any account, the screen goes white and I can't see the project any more.

**To Reproduce**
* Open one of the default playground projects by clicking on Learn Cadence in the top right corner, then any of the "Open Project" boxes. 
* After the new page opens, click on any of the accounts in the accounts section.
* See the white screen

**Expected behavior**
Expected to open an account view

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.5
 - Browser:  Chrome
 - Version: 

**Additional context**

**Comment by bthaile** [comment]
Thanks submitting a bug. I see the error that causes the issue. There are no deployed contracts.

![image](https://github.com/onflow/flow-playground/assets/3970376/bdc3fd27-be53-41e6-b4de-d657a359b521)

**Comment by bthaile** [comment]
@joshuahannan  can you verify this bug has been fixed

**Comment by joshuahannan** [comment]
Looks good to me! Thanks for fixing. I'll close this issue
