### ISSUE TITLE
Clicking on the menu collapse button just turns the whole playground white

### ISSUE THREAD

**Issue by muttoni** [onflow/flow-playground#671]
**Describe the bug**
When clicking on the collapse arrow (I'm assuming that's what it is) just breaks the whole playground.

![image](https://github.com/onflow/flow-playground/assets/27052451/1e57d5e9-bdb6-4691-9b5b-b7a0cb2f6e25)

**To Reproduce**

1. open the playground
2. click on the collapse arrow shown above

**Expected behavior**
I expect that arrow to collapse something, or at least not be visible if it doesn't do anything.

**Screenshots**
![image](https://github.com/onflow/flow-playground/assets/27052451/1e57d5e9-bdb6-4691-9b5b-b7a0cb2f6e25)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 112

**Additional context**

**Comment by bthaile** [comment]
released fix and is working, closing
