### ISSUE TITLE
Enable attachments on Playground

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-playground#673]
[Attachments](https://github.com/onflow/flow-emulator/pull/360) were included in [flow-emulator v0.47.0](https://github.com/onflow/flow-emulator/releases/tag/v0.47.0) and are currently enabled on Testnet. 

It would be helpful for developers to be able to prototype with attachments on Playground in addition to their local environments.

**Additional context**
Working on a tutorial to cover attachments for which a Playground project would be extremely helpful.

**Comment by bthaile** [comment]
Thanks for the heads up. 
Create issue to get attachments supported in language server
https://github.com/onflow/cadence-tools/issues/117

**Comment by bthaile** [comment]
fixed, closing
