### ISSUE TITLE
flow token contract doesn't compile

### ISSUE THREAD

**Issue by Braviti0** [onflow/flow-playground#676]
**Describe the bug**
Valid contract does not deploy on flow playground

**To Reproduce**
copy and paste the official flow token contract
copy and paste the official flow fungible token contract interface
deploy the latter and then the former
trying to deploy the former (flow token contract fails)

**Expected behavior**
It says unexpected error

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Additional context**

**Comment by bthaile** [comment]
The flow token contract takes an `authAccount` in the init method, playground doesn't support that.

Playground needs display to the user that functionality isn't supported.
