### ISSUE TITLE
Surface Events along side Logs and Errors

### ISSUE THREAD

**Issue by shaununderwood** [onflow/flow-playground#679]
**Is your feature request related to a problem? Please describe.**
Events are critical to contract development, and one has to root around inside the js console to find them.

**Describe the solution you'd like**
Along side Logs and Erros, a new tab showing the events emited by the most recent transaction.
A history of events, like one has in logs, is O.K. but frankly just having the most recent transaction's events would be amazing.

**Describe alternatives you've considered**
Routing around the js console, but its horrid. Logging out details IS NOT A SUBSTITUTE. Events have identifiers and surfacing those at dev time is highly impactful to ensure interoperability with other off-chain systems.

**Additional context**
Please!  I'm certain I've seen this request here before and it just gets deleted and nothing done about it. Out of everything else I've seen in the issues list, nothing seems more important than surfacing events.

**Comment by bthaile** [comment]
When a transaction is sent the api does send back events. 

```json
[
  {
    "type": "A.0000000000000005.SimpleContract.SimpleEvent",
    "values": [
      "{\"value\":\"message\",\"type\":\"String\"}\n"
    ],
    "__typename": "Event"
  }
]
```
it's possible to add a new tab called `events` and simple deserialize the json. Just how the `log` tab does.

**Comment by bthaile** [comment]
events have been added to `Log` tab. Thanks for the issue.
![image](https://github.com/onflow/flow-playground/assets/3970376/256fe94e-6ae7-4816-8ba8-b20bdd890319)
