### ISSUE TITLE
Cannot deploy FlowToken contract on Playground.

### ISSUE THREAD

**Issue by temt-ceo** [onflow/flow-playground#690]
**Describe the bug**
Previously, I remember I was able to deploy FlowToken contract on Playground by the following steps. But now a days, it seems becoming impossible. So I am reporting this issue.

**To Reproduce**
1. deploy Testnet's Fungible Token contract to account 0x01 on PlayGround.
FungibleToken contract: https://flow-view-source.com/testnet/account/0x9a0766d93b6608b7/contract/FungibleToken
Screenshots:
<img width="1427" alt="スクリーンショット 2023-06-08 18 52 10" src="https://github.com/onflow/flow-playground/assets/58613670/0ca4fe33-1cba-451d-b69b-0a45fedeae25">

2. deploy Testnet's Flow Token contract to account 0x01 on PlayGround.
FlowToken contract: https://flow-view-source.com/testnet/account/0x7e60df042a9c0868/contract/FlowToken
Screenshots:
<img width="1440" alt="スクリーンショット 2023-06-08 18 56 46" src="https://github.com/onflow/flow-playground/assets/58613670/1937495a-bd29-457c-b26d-112b95653da3">

3. it becomes unrecognized error. "Oops! Something went wrong. If you'd like, please report the Bug. Thank you!"

**Expected behavior**
Can deploy FlowToken contract on Playground.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 113.0.5672.126 

**Additional context**
Thank you in advance.

**Comment by bthaile** [comment]
Flow token takes an AuthAccount in init, playground doesn't support that behavior. 
We'll be adding a error message in Contract Arguments after we support contract arguments.

**Comment by temt-ceo** [comment]
Okay, I understand.

**Comment by fotescodev** [comment]
@bthaile can we update the error message for this specific error.
