### ISSUE TITLE
types in playground do not fit mainnet behavior

### ISSUE THREAD

**Issue by Braviti0** [onflow/flow-playground#691]
**Describe the bug*
lets say type<@flowToken.Vault>.identifier = A.(flowtoken address).FlowToken.Vault
but in playground
type<@flowToken.Vault>.identifier = A.(anyaddress).FlowToken.Vault
why

**To Reproduce**
[Steps to reproduce the behavior:](https://play.flow.com/12bc4671-0081-4bfc-8b91-edf3c5cf590a?type=contract&id=9b2ad784-af5e-4ce1-9a44-2f241dbf878f)

**Expected behavior**
troublesome behavior

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bthaile** [comment]
Adding Notes:
getting this error when loading project. 
![image](https://github.com/onflow/flow-playground/assets/3970376/32cba3ef-ac71-4f29-9c67-68b1b2c8e0f4)
