### ISSUE TITLE
Add Hybrid Custody Scaffold to Playground

### ISSUE THREAD

**Issue by fotescodev** [onflow/flow-playground#711]
Currently there are no existing Playground Tutorials for Hybrid Custody. Need to port whatever is referenced in Flow CLI Scaffold to Playground Tutorial:

![Image](https://github.com/onflow/flow-playground/assets/44682521/3ac36d29-f16a-4408-bc4c-3608b3b8b7c2)

**Comment by bthaile** [comment]
The hybrid custody scaffold is located here https://github.com/onflow/hybrid-custody-scaffold
There are a bunch of files:
12 contracts
44 scripts
38 transactions

That is a lot of files. Include them all? @fotescodev

**Comment by fotescodev** [comment]
No no, we are only talking about the Cadence code specifically @bthaile

**Comment by bthaile** [comment]
in https://github.com/onflow/hybrid-custody-scaffold,
@sisyphusSmiling can you help reduce down the hybrid custody files. So that developers that understand hybrid custody can start playing around with the contracts.

**Comment by sisyphusSmiling** [comment]
@bthaile I did my best to organize and simplify a walkthrough in the README, going from walletless onboarding to linking parent & child accounts. Do you think the README would be sufficient for an initial tutorial?

**Comment by sisyphusSmiling** [comment]
Following up on Discord discussion, I"ll work on minimizing transactions for the app dev persona and will update here once those changes have been made to the scaffold.

**Comment by sisyphusSmiling** [comment]
[PR pushed](https://github.com/onflow/hybrid-custody-scaffold/pull/4) in HC scaffold repo, feedback welcome
