### ISSUE TITLE
The contract is deployed but not recognized in some transactions

### ISSUE THREAD

**Issue by jazdevv** [onflow/flow-playground#713]
**Describe the bug**
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bthaile** [comment]
Need to know a bit more information to debug this. 
Do you have a shareable project?

**Comment by jazdevv** [comment]
Its been some time , but an example is the FlowToken , its not avaulable

**Comment by bthaile** [comment]
This is prob a dup if you are trying to deploy FlowToken. Playground does not support passing in AuthAccount into `init` method
https://github.com/onflow/flow-playground/issues/714
