### ISSUE TITLE
Cadence code is not deploying

### ISSUE THREAD

**Issue by irshit** [onflow/flow-playground#714]
**Describe the bug**
Code is not deployoing

**Screenshots**

![Screenshot (16)](https://github.com/onflow/flow-playground/assets/131376622/8e4b5d2a-81f5-4be2-af70-ec7af0d158a1)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [ chrome]
 - Version []

**Comment by bthaile** [comment]
Playground doesn't support passing in AuthAccount into `init` try removing the dep and deploying. 
Known bug, we are working on a release for better messaging

**Comment by unmani-shinde** [comment]
@bthaile I removed Auth Acount from `init` but I'm still facing the same issue. I'm using Microsoft Edge

**Comment by bthaile** [comment]
Do you have a project link, so I can try in our staging environment?

**Comment by nialexsan** [comment]
I'm closing this issue as a part of triage
feel free to reopen it if it still an issue
