### ISSUE TITLE
"user error: maximum number of 10 projects reached"

### ISSUE THREAD

**Issue by bz-hashtag-0780** [onflow/flow-playground#722]
**Describe the bug**
I can't use the new Flow playground at all. Can't deploy a contract, run a script or anything. It just keeps giving me the error.
"user error: maximum number of 10 projects reached"

![Screenshot 2023-07-30 at 16 36 51](https://github.com/onflow/flow-playground/assets/88026162/a8d18a39-ed4d-4c06-9425-57161e5fa060)

**Comment by nialexsan** [comment]
max set to 50
https://github.com/onflow/flow-playground/blob/5e2bf80ccae3ffbeb3e8f57d0ce4f4a1aad4a7d4/src/components/LeftSidebar/NewProjectButton.tsx#L8
