### ISSUE TITLE
Error parsing arguments when trying to execute a script or transaction

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-playground#731]
**Describe the bug**

When trying to execute any script or transaction with arguments, nothing happens. Looking at the logs I see "Error parsing arguments" errors.

**To Reproduce**
- Visit https://play.flow.com/678d24b8-17f2-4451-99ac-d59ed0cfb056?type=script&id=local-script-temp-0
- Choose any transaction or script with arguments and click execute
- If you open the log, you should see "Error parsing arguments" error

**Expected behavior**
The flow playground UI should successfully parse the script/transaction arguments and show the appropriate inputs so that the user can specify those arguments before execution. No "Error parsing arguments" should be shown.

**Screenshots**
![Screenshot 2023-08-19 at 12 51 11](https://github.com/onflow/flow-playground/assets/36109955/b3402453-36fd-4040-96c9-94fdc9dd1562)

**Desktop (please complete the following information):**
 - OS: MacOS 13.1
 - Browser: Chrome 115.0.5790.170

**Comment by bthaile** [comment]
A few changes I think need to be made to this project.

1. Do you see a syntax error in FLOATEvents cadence code?

2. accounts have changed to use `0x01...0x05`

3. I think if you make those changes everything would work. Then redeploy the contracts.
![image](https://github.com/onflow/flow-playground/assets/3970376/9e492f60-3ba4-49f2-ab2c-05a468ab2840)

**Comment by bartolomej** [comment]
@bthaile Ah I see! I haven't noticed that this contract wasn't yet deployed and that it contains errors.

I guess I would expect that if the referenced/imported contract isn't deployed, it would return some kind of Cadence error saying "couldn't find this contract in this account" or something like that, instead of displaying that confusing "error parsing arguments" error.

Also, this issue isn't really blocking me, I just saw this link in Float's repo and wanted to play around with it a bit. But yeah, it looks like that playground project is a bit out of date / unmaintained, so not a big deal.

I just wonder if we could somehow better handle cases where an existing playground won't work with the current version of the playground to cause less confusion. Maybe there is an easy way to detect that and just say "This project may be incompatible with this playground version"?

**Comment by nialexsan** [comment]
the issue seems to be resolved with a new version of the language server
feel free to reopen the issue if it still exists
