### ISSUE TITLE
Automated Test for Playground Tutorials

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow-playground#78]
Context:

Automated Test Suite for Playground that checks all tutorial examples are working.

Definition of Done:

All contracts in tutorials working
All transactions in tutorials working
More checks to be done

**Comment by 10thfloor** [comment]
Issue moved to [onflow/flow-playground-tutorials #2](https://github.com/onflow/flow-playground-tutorials/issues/2) via [**ZenHub**](https://www.zenhub.com/)
