### ISSUE TITLE
unable to deploy my contract

### ISSUE THREAD

**Issue by pnjn10** [onflow/flow-playground#784]
Tried to deploy a basic nft contract but got an error

**To Reproduce**
Just try to deploy the example given in here : https://cadence-lang.org/docs/1.0/tutorial/non-fungible-tokens-1

![Screenshot 2024-08-24 at 1 12 20 AM](https://github.com/user-attachments/assets/a39194a5-d673-4759-9ed8-5ed7da325d62)

**Comment by joshuahannan** [comment]
@pnjn10 Sorry about the delay in getting this fixed. Are you still seeing this error? It should work now for the first 4 tutorials
