### ISSUE TITLE
BUG: Playground thinks that transactions with multiple Account entitlements have multiple signers

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-playground#804]
**Describe the bug**
When opening up a transaction with an account object with multiple entitlements, the playground incorrectly thinks that it requires multiple signers and won't let you submit the transaction without selecting a second signer.

**To Reproduce**
* Open up https://play.flow.com/ddf0177e-81c8-4512-ac2e-28036b1a3f89
* Click on the "Load Hello" transaction.
* See that there is only one `&Account` in the reference, but it still asks for two signers.
* If you do select a second signer, the transaction fails because it only expects one signer

**Expected behavior**
Expected to be able to sign with a single signer

**Screenshots**
![Screenshot 2024-09-17 at 5 02 43 PM](https://github.com/user-attachments/assets/c0fddbed-13d9-4187-9faa-cf4374924162)

**Desktop (please complete the following information):**
 - OS: MacOSX Sonoma 14.6.1 
 - Browser: Chrome
 - Version: 128.0.6613.138

**Additional context**

**Comment by joshuahannan** [comment]
@nialexsan It looks like you only made the fix for transactions with 2 entitlements. If I have a transaction with 3 entitlements, it still thinks that there should be three signers when there should only be one. Can we make sure that this is true for any number of entitlements?

**Comment by nialexsan** [comment]
@joshuahannan do you have a transaction snippet you're using?

**Comment by jribbink** [comment]
If possible I would strongly recommend using the Cadence parser https://www.npmjs.com/package/@onflow/cadence-parser.  Regex parsing transaction args is just a nightmare and we've been down this rabit hole a bunch of times in Flow JS Testing and Flow Cadut.

That being said, those repos have had their regex updated for Cadence 1.0, so you can also look here for code for parsing the args @nialexsan

**Comment by joshuahannan** [comment]
I just forgot to do a hard refresh. My bad! I'll close this
