### ISSUE TITLE
Support upgradable contracts

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-playground#84]
**Describe the bug**
Currently Playground does not support `signer.contracts.update__experimental`

**To Reproduce**
Attempt to upgrade a contract in Playground and see the error: 
`AuthAccount doesn't have a member contracts`

**Expected behavior**
No error, contract is updated using new API

**Additional context**
Should update the FAQ on the docs site once these changes are merged:
https://docs.onflow.org/intro/FAQ/#how-would-i-upgrade-a-contract

**Comment by 10thfloor** [comment]
@timmymmit @joshuahannan @turbolent tagging for visibility
<img width="860" alt="Screen Shot 2021-01-04 at 12 33 05 PM" src="https://user-images.githubusercontent.com/901466/103577080-ff428380-4e88-11eb-9a0b-88ffbb4d3241.png">

**Comment by joshuahannan** [comment]
I think this is just because the playground doesn't support the latest version of Cadence yet. It is still set to Cadence 0.7, which is pretty old. Once we update the playground, it should fix this issue

**Comment by 10thfloor** [comment]
Closing, this is working now.

**Comment by turbolent** [comment]
@10thfloor Are you sure this works now? This might work in the FE, but the BE still needs to be updated: The BE is still at Cadence v0.8, this PR updates it to v0.12: https://github.com/dapperlabs/flow-playground-api/pull/77
